"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import {useEffect,useState,type MouseEvent} from "react";
import {languageOptions,translations,type Language} from "../i18n";
import {PublicDesignerRanking} from "../live-flows";

const conceptEssayZh=[
"《WHAT 100 PEOPLE DO TO A GAME》是一项持续发生的参与式艺术计划。它从一个未完成的游戏出发，但真正被观察的并不是游戏能否成为一个标准产品，而是一百位彼此不同的人如何在接触、理解、误读、修改和传递它的过程中，让同一个起点逐渐产生无法预先设计的方向。每位参与者都不是被动的测试者，也不需要拥有专业背景。一次回答、一条规则、一张照片、一段声音、一个版本、一场对话或一次拒绝，都可能成为作品的一部分。",
"这里的“游戏”更像一种可以被共同触碰的媒介：它提供有限的边界，也留下足够多的空白。参与者可以遵循已有规则，也可以指出规则中的问题；可以补充内容，也可以删除内容；可以独自工作，也可以与临时组成的小组讨论。每一次行动都会留下痕迹，后来的参与者会面对前面的人已经改变过的材料，因此没有任何人面对的是完全相同的作品。作品不是沿着直线完成，而是在不断叠加、偏离和重新解释中形成。",
"数字网站承担的是入口、记录与协作空间，而不是游戏本体。公开访问者可以阅读项目概念，了解参与这项计划的人；收到邀请码的人才会进入具体的任务、问卷、版本链接、照片日志和私密小组。这样的分层不是为了制造神秘感，而是为了让公开信息与私人协作保持清楚边界，让不同年龄、语言和经验的人知道自己正在进入什么空间，以及自己的内容会被谁看到。",
"项目特别重视低压力参与。参与者无需注册公开账号，不必展示真实姓名，也不需要一次完成全部内容。任务可以保存为草稿，反馈可以之后修改，文件上传失败时应当能够重新尝试。界面尽量减少同时出现的选择，并通过明确的状态告诉使用者内容是否已经保存。这样的设计既考虑注意力容易分散的人，也考虑第一次使用数字协作工具的人，以及阅读、行动或感知方式不同的人。",
"一百并不是把人简化为数量。相反，它提醒项目必须面对差异：语言、地区、年龄、身体条件、教育背景、网络环境、游戏经验和表达习惯都会影响一个人如何理解同一件事。系统提供多语言入口，并允许文字、图片、声音、视频和文件等多种表达方式。没有一种表达天然高于另一种，也不是所有人都必须留下同样多的内容。参与可以很短，也可以持续很久；沉默、犹豫和中途退出同样被视为真实经验。",
"私密小组用于承载需要更稳定关系的讨论。只有项目 Owner 可以创建小组和决定成员，参与者只能看到自己被加入的空间。小组内可以建立不同文字频道、发送与修改消息、回应他人的内容、共享文件，并查看当前成员。群组内容不会自动变成公开材料；如果未来需要公开其中的片段，应再次确认语境、署名方式和参与者意愿。隐私不是附加选项，而是作品结构的一部分。",
"版本记录使变化能够被追踪。项目不会把最新版本包装成唯一正确的结果，而是保留每个阶段的链接、说明和反馈，让人看见一条规则为何出现、一段内容为何消失、一次讨论如何改变后续决定。照片日志保存过程中的现场、物件和行动，但它不是装饰性的宣传相册，而是另一种研究材料。文字无法说明的关系，有时会在图像、声音或时间顺序中被重新发现。",
"贡献度用于帮助整理劳动与责任，不用来判断谁更有价值。策划、设计、测试、翻译、记录、照顾、提出问题、维护秩序和修复错误都是不同形式的贡献。公开的共同创作者页面会持续更新名单顺序，但分数只是项目管理中的一种线索，不能完整代表一个人的影响。Owner 负责记录变动，同时需要保留原因，使排名不会成为脱离过程的竞争游戏。",
"最终，这项计划关心的不是一百个人能否把一个游戏做得更大、更快或更像市场上的成品，而是共同作者关系如何改变创作本身。当控制权被逐步分散，原作者需要学会倾听、等待和接受不确定性；参与者也需要决定自己愿意承担多少责任。网站保存这些决定的过程，使作品既能继续被修改，也能留下可回看的档案。它邀请人们进入的不是一个已经完成的世界，而是一项仍然允许被改变的共同实践。"
];
const conceptEssayEn=["WHAT 100 PEOPLE DO TO A GAME is an ongoing participatory art project that begins with an unfinished game and follows how one hundred different people interpret, alter, question, document, and pass it forward. Participants are not passive testers. A rule, response, image, sound, conversation, refusal, or revision can all become part of the work.","The website is the project’s entrance, archive, feedback centre, and private collaboration space—not the game itself. Public visitors can read the concept and meet the people involved. Invited participants can access tasks, surveys, builds, journals, files, and private groups. This separation keeps public information and private collaboration legible.","The project values low-pressure participation, anonymity, accessibility, multilingual access, recoverable drafts, and different forms of expression. Contribution is used to make labour and responsibility visible, not to measure anyone’s worth. The work remains open to change while preserving the decisions, disagreements, and care that shaped it."];

type PublicView="concept"|"people";

export function PublicPages({initialView}:{initialView:PublicView}){const [lang,setLang]=useState<Language>("zh");const [view,setView]=useState<PublicView>(initialView);useEffect(()=>{queueMicrotask(()=>{const saved=localStorage.getItem("hundred-language") as Language|null;if(saved&&translations[saved])setLang(saved)});const sync=()=>setView(location.pathname==="/people"?"people":"concept");addEventListener("popstate",sync);fetch("/api/designers",{cache:"no-store"}).then(r=>r.ok?r.json():null).then(data=>{if(data?.designers)sessionStorage.setItem("w100-designers-cache",JSON.stringify(data.designers))}).catch(()=>undefined);return()=>removeEventListener("popstate",sync)},[]);useEffect(()=>{localStorage.setItem("hundred-language",lang);document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr"},[lang]);useEffect(()=>{document.title=view==="concept"?"Concept — WHAT 100 PEOPLE DO TO A GAME":"People — WHAT 100 PEOPLE DO TO A GAME"},[view]);const go=(next:PublicView)=>(event:MouseEvent<HTMLAnchorElement>)=>{event.preventDefault();if(view===next)return;history.pushState({},"",next==="concept"?"/concept":"/people");setView(next);window.scrollTo(0,0)};const t=translations[lang];return <main className={`publicPage ${view==="concept"?"conceptPage":"peoplePage"}`}><header className="top"><a className="mark" href="/">WHAT 100 PEOPLE DO TO A GAME</a><nav aria-label={lang==="zh"?"公开页面":"Public pages"}><a className={view==="concept"?"active":""} href="/concept" onClick={go("concept")}>Concept</a><a className={view==="people"?"active":""} href="/people" onClick={go("people")}>{lang==="zh"?"共同创作者":"People"}</a></nav><label className="languagePicker"><span><b aria-hidden="true">🌐</b>{lang==="zh"?"语言":"LANGUAGE"}</span><select value={lang} onChange={e=>setLang(e.target.value as Language)}>{languageOptions.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label></header>{view==="concept"?<section className="conceptStandalone"><span className="kicker">CONCEPT / {t.landing.conceptLabel}</span><h1>{t.landing.conceptA}<br/>{t.landing.conceptB}<br/>{t.landing.conceptC}</h1><div className="conceptEssay">{(lang==="zh"?conceptEssayZh:conceptEssayEn).map((p,i)=><p key={i}>{p}</p>)}</div><a className="peopleCta" href="/people" onClick={go("people")}>{lang==="zh"?"前往共同创作者页面":"Go to the People page"} →</a></section>:<PublicDesignerRanking lang={lang}/>}<footer className="copyright">© Huie Chen. All rights reserved.</footer></main>}

export function ConceptPage(){return <PublicPages initialView="concept"/>}
