"use client";
import {useEffect,useMemo,useState} from "react";
import {questions,type Lang,type Question} from "./questions";
type Answers=Record<string,string|string[]>;
const KEY="what100-survey-draft-v1";
const sections:Record<string,{n:string;zh:string;en:string;noteZh:string;noteEn:string}>={
 wechatName:{n:"01",zh:"关于你",en:"About you",noteZh:"用于识别你的提交",noteEn:"Identify your response"},
 gameDefinition:{n:"02",zh:"游戏判断",en:"Game perspectives",noteZh:"你的经验、偏好与边界",noteEn:"Experience, taste, and boundaries"},
 mediaPreferences:{n:"03",zh:"媒介与参照",en:"Media & references",noteZh:"带进项目的方法与语言",noteEn:"Methods and languages you bring"},
 gameIdea:{n:"04",zh:"项目想象",en:"Project imagination",noteZh:"想法、期待与顾虑",noteEn:"Ideas, expectations, and concerns"},
 planningLevel:{n:"05",zh:"参与方式",en:"Participation",noteZh:"策划层级、实现方向与投入",noteEn:"Planning, implementation, and commitment"},
};
const groups=[
 ["wechatName"],
 ["gameDefinition","likedGenres","recommendations","wantGenres","avoidGenres","likedConcepts","dislikedConcepts","viewpoint","redLines"],
 ["mediaPreferences","mediaOther","mediaToGame","references"],
 ["gameIdea","favoritePoint","concerns","wantToDo","wantToGain"],
 ["planningLevel","planningDetail","creativeRoles","technicalRoles","participation","additionalThoughts"],
];
const sectionStarts=["wechatName","gameDefinition","mediaPreferences","gameIdea","planningLevel"];
function filled(v:unknown){return Array.isArray(v)?v.length>0:typeof v==="string"&&v.trim().length>0}
export function SurveyApp(){
 const [lang,setLang]=useState<Lang>("zh"),[answers,setAnswers]=useState<Answers>({}),[stage,setStage]=useState<"form"|"review"|"done">("form"),[currentSection,setCurrentSection]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{try{const d=localStorage.getItem(KEY);if(d)setAnswers(JSON.parse(d))}catch{}},[]);
 useEffect(()=>{if(stage!=="done")localStorage.setItem(KEY,JSON.stringify(answers))},[answers,stage]);
 const visible=useMemo(()=>questions.filter(q=>!q.showWhen||(Array.isArray(answers[q.showWhen.id])?(answers[q.showWhen.id] as string[]).includes(q.showWhen.includes):answers[q.showWhen.id]===q.showWhen.includes)),[answers]);
 const completed=visible.filter(q=>filled(answers[q.id])).length;
 const currentQuestions=visible.filter(q=>groups[currentSection].includes(q.id));
 const set=(id:string,v:string|string[])=>setAnswers(a=>({...a,[id]:v}));
 const validate=()=>{const miss=visible.find(q=>q.required&&!filled(answers[q.id]));if(miss){setError(lang==="zh"?`请完成：${miss.zh}`:`Please complete: ${miss.en}`);document.getElementById(miss.id)?.scrollIntoView({behavior:"smooth",block:"center"});return false}setError("");return true};
 const validateSection=()=>{const miss=currentQuestions.find(q=>q.required&&!filled(answers[q.id]));if(miss){setError(lang==="zh"?`请完成：${miss.zh}`:`Please complete: ${miss.en}`);document.getElementById(miss.id)?.scrollIntoView({behavior:"smooth",block:"center"});return false}setError("");return true};
 const move=(next:number)=>{setCurrentSection(next);setError("");scrollTo({top:0,behavior:"smooth"})};
 async function submit(){setBusy(true);setError("");try{const r=await fetch("/api/questionnaire",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({answers,locale:lang})});if(!r.ok)throw new Error((await r.json()).error||"Failed");localStorage.removeItem(KEY);setStage("done")}catch(e){setError(lang==="zh"?"提交失败，请稍后再试。":"Submission failed. Please try again.")}finally{setBusy(false)}}
 if(stage==="done")return <main className="survey-shell survey-confirm"><div className="survey-mark">100</div><p className="eyebrow">WHAT 100 PEOPLE DO TO A GAME</p><h1>{lang==="zh"?"已收到。谢谢你把自己带进来。":"Received. Thank you for bringing yourself into the work."}</h1><p>{lang==="zh"?"你的回答已安全保存。之后若需要补充，请联系主策划。":"Your response has been saved securely. Contact the lead designer if you need to add anything."}</p></main>;
 return <main className="survey-shell"><header className="survey-head"><a className="survey-title" href="/survey">WHAT 100 PEOPLE DO TO A GAME<span>一百个人怎么做游戏</span></a><div className="survey-tools"><span className="survey-progress" aria-label={lang==="zh"?"填写进度":"Progress"}><i style={{width:`${Math.round(completed/visible.length*100)}%`}}/>{completed}/{visible.length}</span><button className="lang-switch" onClick={()=>setLang(lang==="zh"?"en":"zh")}>{lang==="zh"?"EN":"中文"}</button></div></header>
 {currentSection===0?<section className="survey-intro"><p className="eyebrow">PARTICIPANT PORTRAIT · 参与者创作画像</p><h1>{lang==="zh"?"不是让一百个人适应一种游戏。":"Not one game for a hundred people to adapt to."}<br/><em>{lang==="zh"?"是从一百个人出发，形成一件作品。":"A work formed by starting from one hundred people."}</em></h1><div className="intro-grid"><p>{lang==="zh"?"大部分参与者没有游戏制作基础，这不是问题，而是项目的起点。我们把不同经验、判断与媒介带到一起。":"Most participants have no game-making background. That is not a problem; it is the starting point. Different experiences, judgments, and media meet here."}</p><p>{lang==="zh"?"这是实验性、跨媒介的共同创作，不是普通 game jam。观点可以不一致，但讨论必须对事不对人，不得人身攻击。":"This is experimental, cross-media collective creation—not a conventional game jam. Views may differ; critique the work, never the person. Personal attacks are not accepted."}</p></div></section>:<section className="survey-step-head"><p className="eyebrow">{lang==="zh"?"参与者创作画像":"PARTICIPANT PORTRAIT"}</p><h1>{lang==="zh"?sections[sectionStarts[currentSection]].zh:sections[sectionStarts[currentSection]].en}</h1><p>{lang==="zh"?sections[sectionStarts[currentSection]].noteZh:sections[sectionStarts[currentSection]].noteEn}</p></section>}
 {stage==="review"?<section className="review-panel"><p className="eyebrow">{lang==="zh"?"提交前检查":"REVIEW"}</p><h2>{lang==="zh"?"这是你的创作画像":"Your creative portrait"}</h2>{visible.filter(q=>filled(answers[q.id])).map((q,i)=><div className="review-item" key={q.id}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{lang==="zh"?q.zh:q.en}</h3><p>{Array.isArray(answers[q.id])?(answers[q.id] as string[]).map(v=>q.options?.find(o=>o.value===v)?.[lang]||v).join(" · "):answers[q.id]}</p></div></div>)}<div className="survey-actions"><button className="button ghost" onClick={()=>setStage("form")}>{lang==="zh"?"返回修改":"Edit answers"}</button><button className="button primary" disabled={busy} onClick={submit}>{busy?(lang==="zh"?"正在提交…":"Submitting…"):(lang==="zh"?"确认提交":"Submit")}</button></div>{error&&<p className="form-error">{error}</p>}</section>:
 <form className="question-list focused-form" onSubmit={e=>{e.preventDefault();if(!validateSection())return;if(currentSection<groups.length-1)move(currentSection+1);else if(validate()){setStage("review");scrollTo({top:0,behavior:"smooth"})}}}><nav className="section-progress" aria-label={lang==="zh"?"问卷章节":"Survey sections"}>{groups.map((_,i)=><button type="button" key={i} className={i===currentSection?"active":i<currentSection?"done":""} onClick={()=>i<currentSection&&move(i)} aria-current={i===currentSection?"step":undefined}><span>{i<currentSection?"✓":i+1}</span><b>{lang==="zh"?sections[sectionStarts[i]].zh:sections[sectionStarts[i]].en}</b></button>)}</nav>{currentQuestions.map((q)=>{const i=visible.findIndex(v=>v.id===q.id);return <QuestionField key={q.id} q={q} n={i+1} lang={lang} value={answers[q.id]} set={v=>set(q.id,v)}/>})}{currentSection===groups.length-1&&<aside className="proposal-note"><span>PROPOSAL</span><p>{lang==="zh"?"如果你已经形成较为完整、具体的游戏构想，可以参照微信群公告中的提案格式进行整理，并发送给主策划 Hera；也欢迎直接发到群内，作为后续共同讨论的起点。":"If you already have a developed and specific game concept, you may use the proposal format in the WeChat group announcement and send it to lead designer Hera. You are also welcome to share it in the group as a starting point for collective discussion."}</p></aside>}{error&&<p className="form-error sticky-error">{error}</p>}<div className="survey-actions step-actions">{currentSection>0?<button className="button ghost" type="button" onClick={()=>move(currentSection-1)}>{lang==="zh"?"上一步":"Back"}</button>:<span>{lang==="zh"?"草稿会自动保存":"Draft saves automatically"}</span>}<button className="button primary" type="submit">{currentSection<groups.length-1?(lang==="zh"?"继续":"Continue"):(lang==="zh"?"检查并提交":"Review & submit")}</button></div></form>}
 <footer className="survey-footer"><span>WHAT 100 PEOPLE DO TO A GAME</span><a href="/lead">{lang==="zh"?"主策划":"Lead Designer"}</a></footer></main>;
}
function QuestionField({q,n,lang,value,set}:{q:Question,n:number,lang:Lang,value:string|string[]|undefined,set:(v:string|string[])=>void}){const label=lang==="zh"?q.zh:q.en;return <section className="question" id={q.id}><div className="q-number">{String(n).padStart(2,"0")}</div><div className="q-body"><label className="q-label">{label}{q.required&&<sup>*</sup>}</label>{(q.type==="text"||q.type==="textarea")&&(q.type==="textarea"?<textarea rows={4} value={(value as string)||""} placeholder={lang==="zh"?q.placeholderZh:q.placeholderEn} onChange={e=>set(e.target.value)}/>:<input value={(value as string)||""} placeholder={lang==="zh"?q.placeholderZh:q.placeholderEn} onChange={e=>set(e.target.value)}/>)}{(q.type==="single"||q.type==="multi")&&<div className="option-grid">{q.options?.map(o=>{const selected=q.type==="multi"?((value as string[])||[]).includes(o.value):value===o.value;return <button type="button" className={selected?"option selected":"option"} key={o.value} onClick={()=>q.type==="multi"?set(selected?((value as string[])||[]).filter(x=>x!==o.value):[...((value as string[])||[]),o.value]):set(o.value)}><span>{selected?"●":"○"}</span>{o[lang]}</button>})}</div>}</div></section>}
