"use client";
import {useSiteLanguage} from "../use-site-language";

export function SurveyHub(){
 const [lang,setLang]=useSiteLanguage();
 const changeLanguage=()=>setLang(lang==="zh"?"en":"zh");
 const zh=lang==="zh";
 return <main className="surveyHub"><header><a href="/">HOW 100 PEOPLE CALL A GAME<span>{zh?"一百个人怎么做游戏":"A collective game project"}</span></a><button aria-label={zh?"切换为英文":"Switch to Chinese"} onClick={changeLanguage}>{zh?"EN":"中文"}</button></header><section className="surveyHubIntro"><div><p>{zh?"项目问卷":"PROJECT SURVEYS"}</p><h1>{zh?"项目问卷":"Project Surveys"}</h1></div><div className="surveyHubStatement"><b>{zh?"从每个人出发，形成共同的创作判断。":"Beginning with each person, forming a shared creative judgment."}</b><span>{zh?"这里集中发布项目各阶段的问卷。每份问卷都会标明用途与开放状态，已提交的内容仅供主策划整理与协调。":"Questionnaires for each project stage are published here. Every survey states its purpose and status; submitted responses are available only to the Lead Designer for coordination."}</span></div></section><section className="surveyCatalogue" aria-label={zh?"问卷列表":"Survey list"}><header><span>NO.</span><span>{zh?"问卷":"SURVEY"}</span><span>{zh?"状态":"STATUS"}</span></header><a href="/survey/participant-portrait"><span className="surveyIndex">01</span><div><small>{zh?"参与者信息 · 创作研究":"PARTICIPANT PROFILE · CREATIVE RESEARCH"}</small><h2>{zh?"参与者创作画像":"Participant Creative Portrait"}</h2><p>{zh?"记录经验、媒介偏好、创作判断、合作意向与投入方式，为后续分组和创作协调提供依据。":"Records experience, media preferences, creative judgment, collaboration interests and availability for grouping and coordination."}</p></div><div className="surveyStatus"><span>{zh?"开放填写":"OPEN"}</span><b className="surveyCta">{zh?"进入问卷":"Open survey"}</b></div></a><a href="/survey/npc-design"><span className="surveyIndex">02</span><div><small>{zh?"角色素材 · 日常观察":"NPC DESIGN · EVERYDAY DETAILS"}</small><h2>{zh?"NPC设计问卷":"NPC Design Survey"}</h2><p>{zh?"收集日常、兴趣、习惯、说话方式与想象中的互动，为游戏里的 100 个 NPC 提供创作素材。":"Collects routines, interests, habits, voices, and imagined interactions as material for the game’s 100 NPCs."}</p></div><div className="surveyStatus"><span>{zh?"开放填写":"OPEN"}</span><b className="surveyCta">{zh?"进入问卷":"Open survey"}</b></div></a><a href="/survey/results"><span className="surveyIndex">R</span><div><small>{zh?"NPC · 调查问卷结果":"NPC · SURVEY RESULTS"}</small><h2>{zh?"查看 NPC 调查问卷结果":"View NPC Survey Results"}</h2><p>{zh?"查看已经提交的 NPC 设计问卷，支持搜索、逐份阅读与导出。":"Review submitted NPC design surveys with search, detailed responses and CSV export."}</p></div><div className="surveyStatus"><span>{zh?"验证码访问":"CODE REQUIRED"}</span><b className="surveyCta">{zh?"查看结果":"View results"}</b></div></a></section><footer><a href="/">{zh?"返回项目首页":"Back to project homepage"}</a><span>© 2026 Huie Chen</span></footer></main>
}
