"use client";
import {useEffect,useMemo,useState} from "react";
import {questions,type Lang,type Question} from "./questions";
type Answers=Record<string,string|string[]>;
const KEY="what100-survey-draft-v1";
const sections:Record<string,{n:string;zh:string;en:string;noteZh:string;noteEn:string}>={
 wechatName:{n:"01",zh:"关于你",en:"About you",noteZh:"用于识别你的提交",noteEn:"Identify your response"},
 gameDefinition:{n:"02",zh:"游戏判断",en:"Game perspectives",noteZh:"你的经验、偏好与边界",noteEn:"Experience, taste, and boundaries"},
 mediaPreferences:{n:"03",zh:"媒介与参照",en:"Media & references",noteZh:"带进项目的方法与语言",noteEn:"Methods and languages you bring"},
 gameIdea:{n:"04",zh:"项目想象",en:"Project imagination",noteZh:"想法、期待与顾虑",noteEn:"Ideas, expectations, and concerns"},
 planningLevel:{n:"05",zh:"参与方式",en:"Participation",noteZh:"策划层级、实现方向与投入",noteEn:"Planning, implementation, and commitment"},
};
const groups=[
 ["wechatName"],
 ["gameDefinition","likedGenres","wantGenres","likedConcepts","avoidGenres"],
 ["mediaPreferences","mediaOther","references"],
 ["gameIdea","favoritePoint","concerns","wantToDo"],
 ["planningLevel","planningDetail","creativeRoles","technicalRoles","participation","additionalThoughts"],
];
const sectionStarts=["wechatName","gameDefinition","mediaPreferences","gameIdea","planningLevel"];
function filled(v:unknown){return Array.isArray(v)?v.length>0:typeof v==="string"&&v.trim().length>0}
function migrateDraftAnswers(source:Answers){
 const next={...source};
 const mergeText=(target:string,sources:string[])=>{
  const values=[next[target],...sources.map(id=>next[id])].filter(v=>typeof v==="string"&&v.trim().length>0) as string[];
  if(values.length)next[target]=[...new Set(values.map(v=>v.trim()))].join("\n\n");
  for(const id of sources)delete next[id];
 };
 mergeText("likedConcepts",["viewpoint"]);
 mergeText("avoidGenres",["dislikedConcepts","redLines"]);
 mergeText("references",["recommendations"]);
 mergeText("wantToDo",["wantToGain"]);
 mergeText("additionalThoughts",["mediaToGame"]);
 return next;
}
export function SurveyApp({embedded=false}:{embedded?:boolean}){
 const [lang,setLang]=useState<Lang>("zh"),[answers,setAnswers]=useState<Answers>({}),[stage,setStage]=useState<"form"|"review"|"done">("form"),[currentSection,setCurrentSection]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(""),[hydrated,setHydrated]=useState(false),[saved,setSaved]=useState(true);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const draft=JSON.parse(raw) as Answers|{answers?:Answers;currentSection?:number};if("answers" in draft){setAnswers(migrateDraftAnswers(draft.answers||{}));setCurrentSection(Math.min(Math.max(Number(draft.currentSection)||0,0),groups.length-1))}else setAnswers(migrateDraftAnswers(draft))}}catch{}finally{setHydrated(true)}},[]);
 useEffect(()=>{if(!hydrated||stage==="done")return;setSaved(false);let idle=0;const timer=setTimeout(()=>{const save=()=>{localStorage.setItem(KEY,JSON.stringify({answers,currentSection}));setSaved(true)};if("requestIdleCallback" in window)idle=window.requestIdleCallback(save,{timeout:800});else save()},650);return()=>{clearTimeout(timer);if(idle&&"cancelIdleCallback" in window)window.cancelIdleCallback(idle)}},[answers,currentSection,hydrated,stage]);
 const visible=useMemo(()=>questions.filter(q=>!q.showWhen||(Array.isArray(answers[q.showWhen.id])?(answers[q.showWhen.id] as string[]).includes(q.showWhen.includes):answers[q.showWhen.id]===q.showWhen.includes)),[answers]);
 const completed=visible.filter(q=>filled(answers[q.id])).length;
 const currentQuestions=visible.filter(q=>groups[currentSection].includes(q.id));
 const sectionComplete=currentQuestions.filter(q=>q.required).every(q=>filled(answers[q.id]));
 const set=(id:string,v:string|string[])=>setAnswers(a=>({...a,[id]:v}));
 const validate=()=>{const miss=visible.find(q=>q.required&&!filled(answers[q.id]));if(miss){setError(lang==="zh"?`请完成：${miss.zh}`:`Please complete: ${miss.en}`);document.getElementById(miss.id)?.scrollIntoView({behavior:"smooth",block:"center"});return false}setError("");return true};
 const validateSection=()=>{const miss=currentQuestions.find(q=>q.required&&!filled(answers[q.id]));if(miss){setError(lang==="zh"?`请完成：${miss.zh}`:`Please complete: ${miss.en}`);document.getElementById(miss.id)?.scrollIntoView({behavior:"smooth",block:"center"});return false}setError("");return true};
 const goTop=()=>{const behavior=matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth";if(embedded)document.querySelector(".embeddedSurvey")?.scrollIntoView({behavior,block:"start"});else scrollTo({top:0,behavior})};
 const move=(next:number)=>{setCurrentSection(next);setError("");goTop()};
 async function submit(){setBusy(true);setError("");try{const r=await fetch("/api/questionnaire",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({answers,locale:lang})});if(r.status===401){setError(lang==="zh"?"请先通过创作者邀请码进入，再提交问卷。":"Enter through creator access before submitting the survey.");return}if(!r.ok)throw new Error((await r.json()).error||"Failed");localStorage.removeItem(KEY);setStage("done")}catch(e){setError(lang==="zh"?"提交失败，请稍后再试。":"Submission failed. Please try again.")}finally{setBusy(false)}}
 if(stage==="done")return <main className={`survey-shell survey-confirm${embedded?" embeddedSurvey":""}`}><div className="survey-mark">100</div><p className="eyebrow">WHAT 100 PEOPLE DO TO A GAME</p><h1>{lang==="zh"?<>已收到<br/>谢谢你把自己带进来</>:<>Received<br/>Thank you for bringing yourself into the work</>}</h1><p>{lang==="zh"?<>你的回答已安全保存<br/>之后若需要补充，请联系主策划</>:<>Your response has been saved securely<br/>Contact the Lead Designer if you need to add anything</>}</p></main>;
 return <main className={`survey-shell${embedded?" embeddedSurvey":""}`}><header className="survey-head">{embedded?<span className="survey-title">参与者创作画像<span>Participant Creative Portrait</span></span>:<a className="survey-title" href="/survey">参与者创作画像<span>Participant Creative Portrait</span></a>}<div className="survey-tools"><span className="draft-status" role="status" aria-live="polite">{saved?(lang==="zh"?"✓ 已保存":"✓ Saved"):(lang==="zh"?"保存中…":"Saving…")}</span><span className="survey-progress" aria-label={lang==="zh"?"填写进度":"Progress"}><i style={{width:`${Math.round(completed/visible.length*100)}%`}}/>{completed}/{visible.length}</span><button className="lang-switch" onClick={()=>setLang(lang==="zh"?"en":"zh")}>{lang==="zh"?"EN":"中文"}</button></div></header>
 {currentSection===0?<section className="survey-intro"><p className="eyebrow">PARTICIPANT PORTRAIT · 参与者创作画像</p><h1>{lang==="zh"?"不是让一百个人适应一种游戏。":"Not one game for a hundred people to adapt to."}<br/><em>{lang==="zh"?"是从一百个人出发，形成一件作品。":"A work formed by starting from one hundred people."}</em></h1><div className="intro-grid"><p>{lang==="zh"?"大部分参与者没有游戏制作基础，这不是问题，而是项目的起点。我们把不同经验、判断与媒介带到一起。":"Most participants have no game-making background. That is not a problem; it is the starting point. Different experiences, judgments, and media meet here."}</p><p>{lang==="zh"?"这是实验性、跨媒介的共同创作。观点可以不一致，但讨论必须对事不对人，不得人身攻击。":"This is experimental, cross-media collective creation. Views may differ; critique the work, never the person. Personal attacks are not accepted."}</p></div></section>:<section className="survey-step-head"><p className="eyebrow">{lang==="zh"?"参与者创作画像":"PARTICIPANT PORTRAIT"}</p><h1>{lang==="zh"?sections[sectionStarts[currentSection]].zh:sections[sectionStarts[currentSection]].en}</h1><p>{lang==="zh"?sections[sectionStarts[currentSection]].noteZh:sections[sectionStarts[currentSection]].noteEn}</p></section>}
 {stage==="review"?<section className="review-panel"><p className="eyebrow">{lang==="zh"?"提交前检查":"REVIEW"}</p><h2>{lang==="zh"?"这是你的创作画像":"Your creative portrait"}</h2>{visible.filter(q=>filled(answers[q.id])).map((q,i)=><div className="review-item" key={q.id}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{lang==="zh"?q.zh:q.en}</h3><p>{Array.isArray(answers[q.id])?(answers[q.id] as string[]).map(v=>q.options?.find(o=>o.value===v)?.[lang]||v).join(" · "):answers[q.id]}</p></div></div>)}<div className="survey-actions"><button className="button ghost" onClick={()=>setStage("form")}>{lang==="zh"?"返回修改":"Edit answers"}</button><button className="button primary" disabled={busy} onClick={submit}>{busy?(lang==="zh"?"正在提交…":"Submitting…"):(lang==="zh"?"确认提交":"Submit")}</button></div>{error&&<p className="form-error">{error}</p>}</section>:
 <form className="question-list focused-form" onSubmit={e=>{e.preventDefault();if(!validateSection())return;if(currentSection<groups.length-1)move(currentSection+1);else if(validate()){setStage("review");goTop()}}}><nav className="section-progress" aria-label={lang==="zh"?"问卷章节":"Survey sections"}>{groups.map((_,i)=>{const available=i<currentSection;return <button type="button" key={i} className={i===currentSection?"active":available?"done":""} disabled={!available} onClick={()=>move(i)} aria-current={i===currentSection?"step":undefined} aria-label={`${i+1}. ${lang==="zh"?sections[sectionStarts[i]].zh:sections[sectionStarts[i]].en}`}><span>{available?"✓":i+1}</span><b>{lang==="zh"?sections[sectionStarts[i]].zh:sections[sectionStarts[i]].en}</b></button>})}</nav><div className={sectionComplete?"focus-note complete":"focus-note"} role="status"><strong>{sectionComplete?(lang==="zh"?"✓ 本部分必填内容已完成":"✓ Required questions complete"):(lang==="zh"?`现在只需完成第 ${currentSection+1} 部分`:`Only focus on section ${currentSection+1} now`)}</strong><span>{sectionComplete?(lang==="zh"?"内容已经保存，可以继续下一部分":"Your work is saved — you can continue"):(lang==="zh"?"可随时离开，回来会从这里继续":"Leave anytime — you will continue here when you return")}</span></div>{currentQuestions.map((q)=>{const i=visible.findIndex(v=>v.id===q.id);return <QuestionField key={q.id} q={q} n={i+1} lang={lang} value={answers[q.id]} set={v=>set(q.id,v)}/>})}{currentSection===groups.length-1&&<aside className="proposal-note"><span>PROPOSAL</span><p>{lang==="zh"?"如果你已经形成较为完整、具体的游戏构想，可以参照微信群公告中的提案格式进行整理，并发送给主策划 Hera；也欢迎直接发到群内，作为后续共同讨论的起点。":"If you already have a developed and specific game concept, you may use the proposal format in the WeChat group announcement and send it to lead designer Hera. You are also welcome to share it in the group as a starting point for collective discussion."}</p></aside>}{error&&<p className="form-error sticky-error">{error}</p>}<div className="survey-actions step-actions">{currentSection>0?<button className="button ghost" type="button" onClick={()=>move(currentSection-1)}>{lang==="zh"?"上一步":"Back"}</button>:<span>{lang==="zh"?"没有标准答案，按真实想法填写即可":"There are no standard answers"}</span>}<button className="button primary" type="submit">{currentSection<groups.length-1?(lang==="zh"?"保存并继续":"Save & continue"):(lang==="zh"?"检查并提交":"Review & submit")}</button></div></form>}
 <footer className="survey-footer"><span>WHAT 100 PEOPLE DO TO A GAME</span>{!embedded&&<a href="/lead">{lang==="zh"?"主策划":"Lead Designer"}</a>}</footer></main>;
}
function QuestionField({q,n,lang,value,set}:{q:Question,n:number,lang:Lang,value:string|string[]|undefined,set:(v:string|string[])=>void}){const label=lang==="zh"?q.zh:q.en;const hasAnswer=filled(value);const selectionCount=Array.isArray(value)?value.length:hasAnswer?1:0;return <section className={hasAnswer?"question answered":"question"} id={q.id}><div className="q-number">{String(n).padStart(2,"0")}</div><div className="q-body"><label className="q-label">{label}{q.required&&<sup>*</sup>}</label>{(q.type==="text"||q.type==="textarea")&&(q.type==="textarea"?<textarea rows={4} value={(value as string)||""} placeholder={lang==="zh"?q.placeholderZh:q.placeholderEn} onChange={e=>set(e.target.value)}/>:<input value={(value as string)||""} placeholder={lang==="zh"?q.placeholderZh:q.placeholderEn} onChange={e=>set(e.target.value)}/>)}{(q.type==="single"||q.type==="multi")&&<div className="option-grid">{q.options?.map(o=>{const selected=q.type==="multi"?((value as string[])||[]).includes(o.value):value===o.value;return <button type="button" aria-pressed={selected} className={selected?"option selected":"option"} key={o.value} onClick={()=>q.type==="multi"?set(selected?((value as string[])||[]).filter(x=>x!==o.value):[...((value as string[])||[]),o.value]):set(o.value)}><span>{selected?"✓":"○"}</span>{o[lang]}</button>})}</div>}{hasAnswer&&<p className="answer-confirmation" role="status">{q.type==="text"||q.type==="textarea"?(lang==="zh"?"✓ 已记录":"✓ Recorded"):(lang==="zh"?`✓ 已选 ${selectionCount} 项`:`✓ ${selectionCount} selected`)}</p>}</div></section>}
