import type { Language } from "./bilingual-i18n";

export type LocaleCopy = {
  access:string;choose:string;publicVisit:string;publicDescription:string;inviteEntry:string;inviteDescription:string;back:string;privateAccess:string;enterCode:string;verifyHint:string;invitationCode:string;verify:string;publicPages:string;concept:string;people:string;language:string;headline:[string,string];subtitle:string;essay:string[];meet:string;collaborators:string;collaboratorIntro:string;filter:string;showAll:string;planning:string;art:string;programming:string;responsibilities:string;profileLink:string;record:string;unassigned:string;openTasks:string;submitted:string;chat:string;gameBuilds:string;
};

export const localeCopy: Record<Language, LocaleCopy> = {
  zh:{access:"选择进入方式",choose:"选择你要进入的部分",publicVisit:"普通访问",publicDescription:"阅读理念与共同创作者页面",inviteEntry:"邀请码进入",inviteDescription:"进入任务、问卷、文件与聊天",back:"返回",privateAccess:"私密访问",enterCode:"填写邀请码",verifyHint:"邀请码验证成功后才能进入协作区域。",invitationCode:"邀请码",verify:"验证并进入",publicPages:"公开页面",concept:"理念",people:"共同创作者",language:"语言",headline:["游戏作为媒介，能走多远","每个人都可以做游戏"],subtitle:"从一百个人出发，而不是先规定一种游戏让所有人适应。",essay:["WHAT 100 PEOPLE DO TO A GAME 从一百个人出发。作品不是由一个预先确定的类型、技术或审美统领，再要求参与者进入同一套方法；它从每个人带来的经验、兴趣、判断和疑问开始，在协作中逐渐形成自己的样子。","我们相信每个人都可以做游戏。游戏的基本材料不是软件和设备，而是规则、行动、反馈、选择以及人与人的关系。一句话、一次轮流、一段声音、一个房间或一件普通物品，都可能成为游戏的起点。制作经验能够扩展实现方式，但不决定一个人是否有资格提出想法。","游戏也不只是娱乐产品。它可以与影像、声音、写作、表演、空间和实体材料交叉，讨论身份、照顾、资源、时间、权力与死亡。重要的不是把所有内容做成传统意义上的游戏，而是理解规则如何组织经验，参与者又能如何行动、感受和改变它。","一百个人不会自然得到一个一致答案，这正是项目的方法。观点可以冲突，媒介可以混合，完整提案和尚未成形的直觉都可以进入讨论。协作不要求抹平差异，但要求对事不对人。最终作品不是一百份意见的简单相加，而是这些意见在选择、试验、修改和共同制作中留下的结构。"],meet:"查看共同创作者",collaborators:"共同创作者",collaboratorIntro:"按分工查看负责人。每位共同创作者都有自己的项目名片。",filter:"按分工筛选",showAll:"再次点击可查看全部共同创作者",planning:"策划",art:"美术",programming:"编程",responsibilities:"分工",profileLink:"个人链接",record:"参与记录",unassigned:"分工待补充",openTasks:"开放任务",submitted:"已提交",chat:"聊天",gameBuilds:"游戏版本"},
  en:{access:"Choose how to enter",choose:"Choose where to begin",publicVisit:"Public visit",publicDescription:"Read the concept and meet the contributors",inviteEntry:"Enter with invitation",inviteDescription:"Access tasks, surveys, files, and chat",back:"Back",privateAccess:"Private access",enterCode:"Enter invitation code",verifyHint:"The collaboration area opens after the invitation is verified.",invitationCode:"Invitation code",verify:"Verify and enter",publicPages:"Public pages",concept:"Concept",people:"Contributors",language:"Language",headline:["How far can games go as a medium","Anyone can make a game"],subtitle:"Begin with one hundred people, rather than asking everyone to adapt to one predetermined game.",essay:["WHAT 100 PEOPLE DO TO A GAME begins with one hundred people. It does not begin by fixing a genre, technology or visual language and then asking everyone to work inside it. The work takes shape through the experiences, interests, judgments and questions that each person brings.","We believe anyone can make a game. The fundamental materials of games are not software and devices, but rules, actions, feedback, choices and relationships. A sentence, a turn, a sound, a room or an ordinary object can become a starting point. Experience can expand how an idea is realised, but it does not decide who is entitled to have one.","Games are more than entertainment products. They can cross into moving image, sound, writing, performance, space and physical material, and they can address identity, care, resources, time, power and death. The aim is not to force every contribution into a conventional game, but to understand how rules organise experience and how participants may act, feel and alter it.","One hundred people will not naturally produce one answer; that is the method. Views may conflict, media may mix, and both developed proposals and unfinished intuitions can enter the discussion. Collaboration does not erase difference, but it does require critique of the work rather than the person. The final piece is not a sum of one hundred opinions. It is the structure those opinions leave behind through selection, testing, revision and collective production."],meet:"Meet the contributors",collaborators:"Contributors",collaboratorIntro:"Filter by discipline to see who is responsible. Every contributor has a project card.",filter:"Filter by discipline",showAll:"Select again to show everyone",planning:"Planning",art:"Art",programming:"Programming",responsibilities:"Responsibilities",profileLink:"Profile link",record:"Participation",unassigned:"Responsibilities to be added",openTasks:"Open tasks",submitted:"Submitted",chat:"Chat",gameBuilds:"Game builds"},
};
