"use client";

import {useEffect,useState,type FormEvent,type MouseEvent} from "react";

type Lang="zh"|"en";
const copy={
 zh:{language:"语言",access:"选择进入方式",choose:"选择你要进入的部分",publicVisit:"普通访问",publicDescription:"阅读项目理念与共同创作者页面",inviteEntry:"邀请码进入",inviteDescription:"创作者协作区",back:"返回",privateAccess:"私密访问",enterCode:"填写邀请码",intro:"参与者填写微信群聊名和邀请码；主策划直接输入主策划验证码。",welcome:"创作区用于记录项目中的实际工作。",welcomeDetail:"不要求游戏制作经验。草图、文字、参考资料和未完成文件都可提交。",name:"微信群聊名（参与者）",namePlaceholder:"填写微信群聊名",code:"邀请码",verify:"验证并进入",entering:"正在进入…",required:"参与者请填写自己的微信群聊名。",error:"邀请码验证成功后才能进入协作区域。",networkError:"网络异常，请检查网络后重试。",copyright:"© 2026 HuieChen. 版权所有。"},
 en:{language:"Language",access:"Choose access",choose:"Choose where to begin",publicVisit:"Public visit",publicDescription:"Read the project concept and contributors",inviteEntry:"Invitation access",inviteDescription:"Creator Workspace",back:"Back",privateAccess:"Private access",enterCode:"Enter invitation",intro:"Participants enter their WeChat group name and invitation code. The Lead Designer enters the lead access code.",welcome:"The workspace records active project work.",welcomeDetail:"Game-making experience is not required. Sketches, text, references, and unfinished files may be submitted.",name:"WeChat group name (participants)",namePlaceholder:"WeChat group name",code:"Invitation code",verify:"Verify and enter",entering:"Opening…",required:"Participants must enter their WeChat group name.",error:"The collaboration area opens after the invitation is verified.",networkError:"Network error. Please check your connection and try again.",copyright:"© 2026 HuieChen. All rights reserved."}
};

export function EntryStudio(){
 const [lang,setLang]=useState<Lang>("zh"),[invite,setInvite]=useState(false),[name,setName]=useState(""),[code,setCode]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const c=copy[lang];
 useEffect(()=>{const saved=localStorage.getItem("hundred-language");const next:Lang=saved==="en"||(!saved&&navigator.language.toLowerCase().startsWith("en"))?"en":"zh";setLang(next);const sync=()=>{const params=new URLSearchParams(location.search);setInvite(params.get("access")==="invite"||params.has("invite"));const token=params.get("invite");if(token)setCode(token)};sync();window.addEventListener("popstate",sync);return()=>window.removeEventListener("popstate",sync)},[]);
 useEffect(()=>{localStorage.setItem("hundred-language",lang);document.documentElement.lang=lang==="zh"?"zh-CN":"en"},[lang]);
 function openInvite(event:MouseEvent<HTMLAnchorElement>){event.preventDefault();history.pushState({},"","/?access=invite");setNotice("");setInvite(true)}
 function closeInvite(event:MouseEvent<HTMLAnchorElement>){event.preventDefault();history.pushState({},"","/");setNotice("");setInvite(false)}
 async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setNotice("");try{const response=await fetch("/api/access",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code,name})});if(!response.ok){const data=await response.json().catch(()=>({})) as {error?:string};setNotice(data.error==="Participant name is required"?c.required:c.error);return}const data=await response.json() as {role:"lead"|"participant"};go(data.role==="lead"?"/workspace?view=journal":"/workspace");return}catch{setNotice(c.networkError)}finally{setBusy(false)}}
 function go(url:string){try{location.href=url}catch{location.replace(url)}setTimeout(()=>{if(!location.href.includes(url))location.href=url},600)}
 const wordmark=<span className="wordmark wordmarkInline"><span>WHAT </span><strong>100 PEOPLE</strong><span> DO TO A </span><strong>GAME</strong></span>;
 const language=<label className="languagePicker"><span><b aria-hidden="true">LANG</b>{c.language}</span><select aria-label={c.language} value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="zh">中文</option><option value="en">English</option></select></label>;
 if(!invite)return <main className="entryGate"><div className="entryTop">{wordmark}{language}</div><section><span className="kicker">{c.access}</span><h1>{c.choose}</h1><div className="entryChoices"><a className="entryChoice" href="/concept"><b>{c.publicVisit}</b><span>{c.publicDescription}</span></a><a className="entryChoice" href="/?access=invite" onClick={openInvite}><b>{c.inviteEntry}</b><span>{c.inviteDescription}</span></a></div></section><footer className="copyright">{c.copyright}</footer></main>;
 return <main className="entryGate inviteGate"><div className="entryTop"><a href="/" onClick={closeInvite}>← {c.back}</a>{language}</div><section><span className="kicker">{c.privateAccess}</span><h1>{c.enterCode}</h1><p>{c.intro}</p><aside className="creatorWelcome"><strong>{c.welcome}</strong><span>{c.welcomeDetail}</span></aside><form className="gateInvite" onSubmit={submit} aria-busy={busy}><label><span>{c.name}</span><input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" maxLength={40} placeholder={c.namePlaceholder}/></label><label><span>{c.code}</span><input value={code} onChange={e=>setCode(e.target.value)} autoComplete="one-time-code" inputMode="numeric" placeholder={c.code}/></label><button className="primary" type="submit" disabled={busy}>{busy?c.entering:c.verify}</button></form>{notice&&<p className="gateError" role="alert">{notice}</p>}</section><footer className="copyright">{c.copyright}</footer></main>;
}
