"use client";

import { useEffect, useMemo, useState } from "react";
import type { Language, Translation } from "./i18n";

type TaskRow={id:string;title_zh:string;title_en:string;body:string|null;submission_status:string|null;updated_at:number|null};
type GroupRow={id:string;name:string;member_count:number;created_at:number};
type MessageRow={id:string;body:string;display_code:string;created_at:number;participant_id:string};
type ParticipantRow={id:string;display_code:string};
type FileRow={id:string;name:string;content_type:string;size:number;created_at:number;participant_id:string};

function shortError(lang:Language){return lang==="zh"?"暂时无法保存，内容仍保留在此设备。":"Could not save yet. Your draft remains on this device."}

export function LiveTasks({t,lang}:{t:Translation;lang:Language}){
 const [tasks,setTasks]=useState<TaskRow[]>([]);const [text,setText]=useState("");const [status,setStatus]=useState("");const [saving,setSaving]=useState(false);
 useEffect(()=>{fetch("/api/tasks",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();const data=await r.json() as {tasks:TaskRow[]};setTasks(data.tasks||[]);const first=data.tasks?.[0];const local=localStorage.getItem(`w100-draft-${first?.id}`);setText(first?.body??local??"")}).catch(()=>setStatus(shortError(lang)))},[lang]);
 const task=tasks[0];
 async function save(submit=false){if(!task)return;setSaving(true);localStorage.setItem(`w100-draft-${task.id}`,text);const res=await fetch("/api/tasks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({taskId:task.id,body:text,status:submit?"submitted":"draft"})}).catch(()=>null);setSaving(false);if(res?.ok){localStorage.removeItem(`w100-draft-${task.id}`);setStatus(submit?(lang==="zh"?"已提交，可以继续修改。":"Submitted. You can still revise it."):t.tasks.saved)}else setStatus(shortError(lang))}
 if(!task)return <div className="page narrow"><div className="kicker">TASK</div><h1>{t.tasks.title}</h1><div className="lock">{lang==="zh"?"暂无开放任务。":"No open task yet."}</div></div>;
 return <div className="page narrow"><div className="kicker">TASK 01 · {task.submission_status||"OPEN"}</div><h1>{lang==="zh"?task.title_zh:task.title_en}</h1><p className="lede">{t.tasks.intro}</p><div className="prompt"><span>{t.tasks.prompt}</span><textarea value={text} onChange={e=>{setText(e.target.value);localStorage.setItem(`w100-draft-${task.id}`,e.target.value)}} onBlur={()=>save(false)} placeholder={t.tasks.placeholder}/><div><small>{text.length} · {saving?(lang==="zh"?"正在保存…":"Saving…"):status||t.tasks.auto}</small><button className="primary" onClick={()=>save(true)} disabled={saving||!text.trim()}>{t.tasks.save} →</button></div></div><LiveUpload t={t} lang={lang} taskId={task.id}/></div>
}

export function LiveSurvey({t,lang}:{t:Translation;lang:Language}){
 const [scale,setScale]=useState(0);const [moment,setMoment]=useState("");const [status,setStatus]=useState("");const [saving,setSaving]=useState(false);
 useEffect(()=>{fetch("/api/surveys",{cache:"no-store"}).then(async r=>{if(!r.ok)return;const data=await r.json() as {response?:{scale?:number;moment?:string}};setScale(data.response?.scale||0);setMoment(data.response?.moment||"")}).catch(()=>undefined)},[]);
 async function submit(){setSaving(true);const res=await fetch("/api/surveys",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scale,moment})}).catch(()=>null);setSaving(false);setStatus(res?.ok?(lang==="zh"?"反馈已安全保存。":"Feedback saved securely."):shortError(lang))}
 return <div className="page narrow"><div className="kicker">PLAYTEST / {t.survey.label}</div><h1>{t.survey.title}</h1><fieldset className="scale"><legend>{t.survey.scale}</legend>{[1,2,3,4,5].map(n=><label key={n}><input type="radio" name="scale" checked={scale===n} onChange={()=>setScale(n)}/><span>{n}</span></label>)}</fieldset><label className="field">{t.survey.moment}<textarea value={moment} onChange={e=>setMoment(e.target.value)}/></label><button className="primary" onClick={submit} disabled={saving||!scale}>{saving?(lang==="zh"?"正在保存…":"Saving…"):t.survey.submit}</button>{status&&<p className="saveStatus" role="status">{status}</p>}</div>
}

export function LiveUpload({t,lang,taskId,groupId,onUploaded}:{t:Translation;lang:Language;taskId?:string;groupId?:string;onUploaded?:()=>void}){
 const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);let completed=0;for(const file of Array.from(files)){const form=new FormData();form.set("file",file);if(taskId)form.set("taskId",taskId);if(groupId)form.set("groupId",groupId);const res=await fetch("/api/uploads",{method:"POST",body:form}).catch(()=>null);if(res?.ok)completed++}setBusy(false);setStatus(completed===files.length?(lang==="zh"?`${completed} 个文件已安全上传。`:`${completed} file(s) uploaded securely.`):(lang==="zh"?`已上传 ${completed}/${files.length} 个文件。`:`Uploaded ${completed}/${files.length} file(s).`));if(completed)onUploaded?.()}
 return <label className={`upload ${busy?"busy":""}`}><input type="file" multiple accept="image/jpeg,image/png,image/webp,image/heic,image/heif,audio/mpeg,audio/wav,audio/mp4,video/mp4,application/pdf,text/plain,.docx,.xlsx,.pptx" onChange={e=>upload(e.target.files)}/><span>＋</span><b>{busy?(lang==="zh"?"正在上传…":"Uploading…"):t.upload.add}</b><small>{status||t.upload.detail}</small></label>
}

export function LiveGroups({t,lang}:{t:Translation;lang:Language}){
 const [groups,setGroups]=useState<GroupRow[]>([]);const [selected,setSelected]=useState("");const [messages,setMessages]=useState<MessageRow[]>([]);const [files,setFiles]=useState<FileRow[]>([]);const [draft,setDraft]=useState("");const [error,setError]=useState("");
 const loadGroups=()=>fetch("/api/groups",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();const data=await r.json() as {groups:GroupRow[]};setGroups(data.groups||[]);setSelected(x=>x||data.groups?.[0]?.id||"")}).catch(()=>setError(lang==="zh"?"需要有效邀请才能查看私密小组。":"A valid invitation is required to view private groups."));
 const loadMessages=(id:string)=>fetch(`/api/messages?groupId=${encodeURIComponent(id)}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();const data=await r.json() as {messages:MessageRow[]};setMessages(data.messages||[])}).catch(()=>setError(lang==="zh"?"你不是这个小组的成员。":"You are not a member of this group."));
 const loadFiles=(id:string)=>fetch(`/api/uploads?groupId=${encodeURIComponent(id)}`,{cache:"no-store"}).then(async r=>{if(!r.ok)return;const data=await r.json() as {files:FileRow[]};setFiles(data.files||[])}).catch(()=>undefined);
 useEffect(()=>{loadGroups()},[]);useEffect(()=>{if(!selected)return;loadMessages(selected);loadFiles(selected);const timer=setInterval(()=>loadMessages(selected),8000);return()=>clearInterval(timer)},[selected]);
 async function send(){if(!draft.trim()||!selected)return;const res=await fetch("/api/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({groupId:selected,body:draft})}).catch(()=>null);if(res?.ok){setDraft("");await loadMessages(selected)}else setError(lang==="zh"?"消息未发送，请重试。":"Message was not sent. Try again.")}
 const group=groups.find(x=>x.id===selected);
 return <div className="page"><div className="kicker">PRIVATE GROUP / {t.groups.label}</div><h1>{group?.name||t.groups.title} <small>{group?`${group.member_count} ${lang==="zh"?"人":"members"}`:""}</small></h1>{groups.length>1&&<div className="groupTabs">{groups.map(g=><button key={g.id} className={selected===g.id?"active":""} onClick={()=>setSelected(g.id)}>{g.name}</button>)}</div>}{!groups.length?<div className="lock">🔒 {error||(lang==="zh"?"你目前还没有加入小组。":"You have not joined a group yet.")}</div>:<><div className="chat liveChat">{messages.length?messages.map(m=><div key={m.id}><b>{m.display_code}</b><p>{m.body}</p><time>{new Date(Number(m.created_at)).toLocaleString(lang)}</time></div>):<div><p>{lang==="zh"?"这是一个新的私密小组。":"This is a new private group."}</p></div>}</div><label className="composer"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")send()}} placeholder={t.groups.placeholder}/><button onClick={send}>{t.groups.send}</button></label><LiveUpload t={t} lang={lang} groupId={selected} onUploaded={()=>loadFiles(selected)}/>{files.length>0&&<div className="groupFiles"><span className="kicker">{lang==="zh"?"群文件":"GROUP FILES"}</span>{files.map(file=><a key={file.id} href={`/api/uploads?id=${encodeURIComponent(file.id)}`} target="_blank" rel="noreferrer"><b>{file.name}</b><small>{(Number(file.size)/1024/1024).toFixed(1)} MB</small></a>)}</div>}<div className="lock">🔒 {t.groups.lock}</div></>}</div>
}

type InvitationRow={id:string;label:string;token_hint:string;display_code:string;participant_id:string;created_at:number;expires_at:number|null;revoked_at:number|null};
export function OwnerOperations({lang,participants,onParticipantsChanged}:{lang:Language;participants:ParticipantRow[];onParticipantsChanged:()=>void}){
 const zh=lang==="zh";const [invitations,setInvitations]=useState<InvitationRow[]>([]);const [label,setLabel]=useState("");const [newToken,setNewToken]=useState("");const [groupName,setGroupName]=useState("");const [members,setMembers]=useState<string[]>([]);const [groups,setGroups]=useState<GroupRow[]>([]);const [status,setStatus]=useState("");
 const load=()=>Promise.all([fetch("/api/invitations",{cache:"no-store"}).then(r=>r.json()),fetch("/api/groups",{cache:"no-store"}).then(r=>r.json())]).then(([a,b])=>{setInvitations(a.invitations||[]);setGroups(b.groups||[])}).catch(()=>setStatus(zh?"管理数据暂时无法读取。":"Management data is temporarily unavailable."));
 useEffect(()=>{load()},[]);
 async function createInvite(){const res=await fetch("/api/invitations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({label:label||undefined,expiresInDays:90})});const data=await res.json();if(res.ok){setNewToken(data.invitation.token);setLabel("");setStatus(zh?"邀请已创建；完整代码只在这里显示一次。":"Invitation created; the full code is shown only once.");await load();onParticipantsChanged()}}
 async function revoke(id:string){await fetch("/api/invitations",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id})});await load()}
 async function copyInvite(){if(!newToken)return;const link=`${location.origin}/?invite=${encodeURIComponent(newToken)}`;await navigator.clipboard.writeText(link);setStatus(zh?"邀请链接已复制。":"Invitation link copied.")}
 async function createGroup(){const res=await fetch("/api/groups",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:groupName,members})});if(res.ok){setGroupName("");setMembers([]);setStatus(zh?"私密小组已建立。":"Private group created.");await load()}}
 const activeInvites=useMemo(()=>invitations.filter(x=>!x.revoked_at),[invitations]);
 return <section className="ownerOperations"><div className="opsGrid"><div className="opsCard"><span className="kicker">INVITATIONS</span><h2>{zh?"真实邀请管理":"Invitation management"}</h2><div className="inlineForm"><input value={label} onChange={e=>setLabel(e.target.value)} placeholder={zh?"邀请备注，例如：第 43 位参与者":"Invitation label"}/><button className="dark" onClick={createInvite}>{zh?"生成邀请":"Create invitation"}</button></div>{newToken&&<div className="tokenReveal"><code>{newToken}</code><button onClick={copyInvite}>{zh?"复制邀请链接":"Copy invitation link"}</button></div>}<div className="miniList">{activeInvites.slice(0,8).map(x=><div key={x.id}><span><b>{x.display_code}</b><small>{x.label||x.token_hint}</small></span><button onClick={()=>revoke(x.id)}>{zh?"撤销":"Revoke"}</button></div>)}</div></div><div className="opsCard"><span className="kicker">PRIVATE GROUPS</span><h2>{zh?"建立私密小组":"Create a private group"}</h2><input value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder={zh?"小组名称":"Group name"}/><div className="memberPicker">{participants.slice(0,30).map(p=><label key={p.id}><input type="checkbox" checked={members.includes(p.id)} onChange={()=>setMembers(x=>x.includes(p.id)?x.filter(id=>id!==p.id):[...x,p.id])}/>{p.display_code}</label>)}</div><button className="dark" onClick={createGroup} disabled={!groupName||!members.length}>{zh?"建立小组":"Create group"}</button><small>{zh?`已有 ${groups.length} 个私密小组。只有 Owner 可以建立。`:`${groups.length} private group(s). Only the Owner can create them.`}</small></div></div>{status&&<p className="saveStatus" role="status">{status}</p>}</section>
}
