"use client";

import { useEffect, useState } from "react";
import { applyTranslationOverrides, languageOptions, translations, type Language, type Translation } from "./i18n";
import { DesignerRosterManager, LiveGroups, LiveJournal, LiveLinks, LiveSurvey, LiveTasks, OwnerContentManager, OwnerOperations, PublicDesignerRanking } from "./live-flows";

type View="home"|"tasks"|"survey"|"links"|"journal"|"groups"|"dashboard";
const views:View[]=["home","tasks","survey","links","journal","groups","dashboard"];
type ContentByLanguage = Record<Language, Record<string, string>>;
const emptyContent=Object.fromEntries(languageOptions.map(({value})=>[value,{}])) as ContentByLanguage;

export function Studio(){
 const [lang,setLang]=useState<Language>("zh");const [view,setView]=useState<View>("home");const [entered,setEntered]=useState(false);const [code,setCode]=useState("");const [notice,setNotice]=useState("");const [joining,setJoining]=useState(false);const [participant,setParticipant]=useState<{id:string;display_code:string}|null>(null);const [content,setContent]=useState<ContentByLanguage>(emptyContent);const t=applyTranslationOverrides(translations[lang],content[lang]);
 useEffect(()=>{queueMicrotask(()=>{const saved=localStorage.getItem("hundred-language") as Language|null;const browser=navigator.language.toLowerCase();setLang(saved&&translations[saved]?saved:browser.startsWith("ja")?"ja":browser.startsWith("en")?"en":"zh")})},[]);
 useEffect(()=>{queueMicrotask(()=>{const params=new URLSearchParams(location.search);const invite=params.get("invite");if(invite){setCode(invite);void join(invite)}else if(params.get("creator")==="1"){setEntered(true);setView("dashboard")}})},[]);
 useEffect(()=>{fetch("/api/participant",{cache:"no-store"}).then(async r=>{if(!r.ok)return;const data=await r.json() as {participant?:{id:string;display_code:string}|null};if(data.participant){setParticipant(data.participant);setEntered(true)}}).catch(()=>undefined)},[]);
 useEffect(()=>{localStorage.setItem("hundred-language",lang);document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr"},[lang]);
 useEffect(()=>{let active=true;const load=()=>fetch("/api/content",{cache:"no-store"}).then(async r=>{if(!r.ok)return;const data=await r.json() as {content?:ContentByLanguage};if(active&&data.content)setContent({...emptyContent,...data.content})}).catch(()=>undefined);load();const timer=setInterval(load,15000);window.addEventListener("content-updated",load);return()=>{active=false;clearInterval(timer);window.removeEventListener("content-updated",load)}},[]);
 useEffect(()=>{if(!entered)return;const record=(kind:string,durationSeconds=0)=>fetch("/api/activity",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,surface:view,durationSeconds}),keepalive:true}).catch(()=>undefined);record("view");const heartbeat=setInterval(()=>record("heartbeat",60),60000);return()=>clearInterval(heartbeat)},[entered,view]);
 async function join(token=code){setJoining(true);setNotice("");const res=await fetch("/api/participant",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token})}).catch(()=>null);setJoining(false);if(res?.ok){const data=await res.json() as {participant:{id:string;display_code:string}};setParticipant(data.participant);setEntered(true);setView("home");history.replaceState({},"",location.pathname)}else setNotice(lang==="zh"?"邀请编号无效、已过期或已被撤销。":"This invitation is invalid, expired, or revoked.")}
 if(!entered)return <main className="landing"><header className="top"><span className="mark">WHAT 100 PEOPLE DO TO A GAME</span><div><LanguageSwitcher lang={lang} setLang={setLang} label={t.language}/><button className="ghost" onClick={()=>{setEntered(true);setView("dashboard")}}>{t.creatorSignIn}</button></div></header>{notice&&<div className="toast errorToast" role="alert">{notice}</div>}<section className="hero"><div className="eyebrow">{t.landing.eyebrow}</div><h1>{t.landing.titleA}<br/><em>{t.landing.titleB}</em></h1><p>{t.landing.subtitle}</p><div className="heroActions"><button className="primary" onClick={()=>document.getElementById("concept")?.scrollIntoView()}>{t.landing.enter} →</button><a href="#concept">{t.landing.concept}</a></div><div className="orbit" aria-hidden="true"/></section><section id="concept" className="concept"><span>CONCEPT / {t.landing.conceptLabel}</span><h2>{t.landing.conceptA}<br/>{t.landing.conceptB}<br/>{t.landing.conceptC}</h2><div className="invite"><label>{t.landing.invite}<input value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")join()}} autoComplete="off"/></label><button className="dark" onClick={()=>join()} disabled={joining||!code.trim()}>{joining?(lang==="zh"?"正在验证…":"Checking…"):t.landing.join}</button><small>{t.landing.noAccount}</small></div></section><PublicDesignerRanking lang={lang}/><Footer text={t.copyright}/></main>;
 const navLabels=[t.nav.overview,t.nav.tasks,t.nav.survey,t.nav.links,t.nav.journal,t.nav.groups,t.nav.dashboard];
 const participantLabel=participant?.display_code||"OWNER";
 return <main className="app"><aside><button className="brand" onClick={()=>setView("home")}>WHAT 100<span>PEOPLE DO TO A GAME</span></button><nav aria-label="Navigation">{views.map((id,i)=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><b>{String(i+1).padStart(2,"0")}</b>{navLabels[i]}</button>)}</nav><div className="asideFoot"><span>{participantLabel}</span></div></aside><section className="workspace"><header className="worktop"><span>LIVE PROJECT</span><div><LanguageSwitcher lang={lang} setLang={setLang} label={t.language}/><span className="privacy">● {t.privacy}</span><button className="avatar" aria-label={participantLabel}>{participantLabel.slice(-2)}</button></div></header>{notice&&<div className="toast">✓ {notice}</div>}{view==="home"&&<Overview t={t} setView={setView} participantCode={participantLabel} lang={lang}/>} {view==="tasks"&&<LiveTasks t={t} lang={lang}/>} {view==="survey"&&<LiveSurvey t={t} lang={lang}/>} {view==="links"&&<LiveLinks t={t} lang={lang}/>} {view==="journal"&&<LiveJournal t={t} lang={lang}/>} {view==="groups"&&<LiveGroups t={t} lang={lang}/>} {view==="dashboard"&&<Dashboard t={t} lang={lang}/>}<Footer text={t.copyright}/></section></main>
}

function LanguageSwitcher({lang,setLang,label}:{lang:Language,setLang:(l:Language)=>void,label:string}){return <label className="languagePicker"><span><b aria-hidden="true">🌐</b>{label} / LANGUAGE</span><select aria-label={`${label} / Language`} value={lang} onChange={e=>setLang(e.target.value as Language)}>{languageOptions.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>}
function Overview({t,setView,participantCode,lang}:{t:Translation,setView:(v:View)=>void;participantCode:string;lang:Language}){const [summary,setSummary]=useState({activeTasks:0,submittedTasks:0,journalEntries:0,gameLinks:0,groups:0,activeSurveys:0});useEffect(()=>{fetch("/api/overview",{cache:"no-store"}).then(async r=>{if(r.ok)setSummary(await r.json())}).catch(()=>undefined)},[]);const cards=[{view:"tasks" as View,title:t.nav.tasks,count:summary.activeTasks},{view:"survey" as View,title:t.nav.survey,count:summary.activeSurveys},{view:"journal" as View,title:t.nav.journal,count:summary.journalEntries}];return <div className="page"><div className="intro"><span>{participantCode}</span><h1>{t.overview.welcome.replace("#042",participantCode)}</h1><p>{t.overview.gentle}</p></div><div className="progress"><div><b>{summary.activeTasks}</b><span>{lang==="zh"?"开放任务":"Open tasks"}</span></div><div><b>{summary.submittedTasks}</b><span>{lang==="zh"?"已提交":"Submitted"}</span></div><div><b>{summary.groups}</b><span>{lang==="zh"?"私密小组":"Private groups"}</span></div><div><b>{summary.gameLinks}</b><span>{lang==="zh"?"游戏版本":"Game builds"}</span></div></div><h2 className="sectionTitle">{t.overview.next}</h2><div className="taskGrid">{cards.map((x,i)=><button key={x.view} className={`task ${["coral","blue","green"][i]}`} onClick={()=>setView(x.view)}><span>{x.count}</span><h3>{x.title}</h3><i>→</i></button>)}</div><div className="note"><span>{t.overview.creator}</span><p>{t.overview.note}</p></div></div>}
type ContributionRow={id:string;display_code:string;contribution_score:number;activity_count:number;last_active_at:number|null};

function Dashboard({t,lang}:{t:Translation,lang:Language}){
 const [rows,setRows]=useState<ContributionRow[]>([]);const [locked,setLocked]=useState(false);const [selected,setSelected]=useState("");const [points,setPoints]=useState("1");const [reason,setReason]=useState("");const [message,setMessage]=useState("");const [search,setSearch]=useState("");const [now]=useState(()=>Date.now());
 const load=()=>fetch("/api/contributions",{cache:"no-store"}).then(async r=>{if(!r.ok){setLocked(true);return}const data=await r.json() as {participants?:ContributionRow[]};setLocked(false);setRows(data.participants||[]);setSelected(x=>x||data.participants?.[0]?.id||"")}).catch(()=>setLocked(true));
 useEffect(()=>{load()},[]);
 async function record(){const res=await fetch("/api/contributions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({participantId:selected,points:Number(points),reason})});if(res.ok){setReason("");setMessage(t.dashboard.success);await load()}else setMessage(t.dashboard.failure)}
 if(locked)return <div className="page narrow"><div className="kicker">{t.dashboard.label}</div><h1>{t.dashboard.lockedTitle}</h1><div className="lock">🔒 {t.dashboard.locked}</div><a className="primary signin" href="/signin-with-chatgpt?return_to=/?creator=1">{t.dashboard.signIn}</a></div>;
 const total=rows.reduce((s,r)=>s+Number(r.contribution_score||0),0);const locale=lang==="zh"?"zh-CN":lang==="ja"?"ja-JP":lang;const filtered=rows.filter(r=>r.display_code.toLowerCase().includes(search.toLowerCase()));
 function exportCsv(){const header=["participant","contribution_score","activity_count","last_active_at"];const data=filtered.map(r=>[r.display_code,r.contribution_score,r.activity_count,r.last_active_at?new Date(Number(r.last_active_at)).toISOString():""]);const csv=[header,...data].map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob(["\uFEFF",csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`w100-participants-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className="page"><div className="kicker">{t.dashboard.label}</div><h1>{t.dashboard.title}</h1><OwnerOperations lang={lang} participants={rows} onParticipantsChanged={load}/><OwnerContentManager lang={lang}/><DesignerRosterManager lang={lang}/><ContentEditor t={t} lang={lang}/><div className="metrics">{[[String(rows.length),t.dashboard.recorded],[String(rows.reduce((s,r)=>s+Number(r.activity_count||0),0)),t.dashboard.events],[String(total),t.dashboard.total],[String(rows.filter(r=>r.last_active_at&&now-Number(r.last_active_at)<86400000).length),t.dashboard.daily]].map(([a,b])=><div key={b}><b>{a}</b><span>{b}</span></div>)}</div><section className="scorePanel"><div><span className="kicker">{t.dashboard.manual}</span><h2>{t.dashboard.manualTitle}</h2></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{rows.map(r=><option key={r.id} value={r.id}>{r.display_code}</option>)}</select><input type="number" min="-1000" max="1000" value={points} onChange={e=>setPoints(e.target.value)} aria-label={t.dashboard.points}/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder={t.dashboard.reason}/><button className="dark" onClick={record} disabled={!selected||!reason}>{t.dashboard.record}</button>{message&&<small>{message}</small>}</section><div className="dashboardTools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={lang==="zh"?"按参与者编号筛选":"Filter by participant code"}/><button className="owner" onClick={exportCsv}>{lang==="zh"?"导出 CSV":"Export CSV"}</button></div><div className="table contributionTable"><div className="tr head"><span>{t.dashboard.person}</span><span>{t.dashboard.score}</span><span>{t.dashboard.activity}</span><span>{t.dashboard.recent}</span></div>{filtered.map(r=><div className="tr" key={r.id}><span>{r.display_code}</span><span><b>{r.contribution_score}</b></span><span>{r.activity_count}</span><span>{r.last_active_at?new Date(Number(r.last_active_at)).toLocaleString(locale):t.dashboard.never}</span></div>)}</div></div>
}

type EditorFields={
 "landing.eyebrow":string;"landing.titleA":string;"landing.titleB":string;"landing.subtitle":string;"landing.conceptA":string;"landing.conceptB":string;"landing.conceptC":string;"overview.note":string;copyright:string;
};
function editorFields(t:Translation):EditorFields{return{"landing.eyebrow":t.landing.eyebrow,"landing.titleA":t.landing.titleA,"landing.titleB":t.landing.titleB,"landing.subtitle":t.landing.subtitle,"landing.conceptA":t.landing.conceptA,"landing.conceptB":t.landing.conceptB,"landing.conceptC":t.landing.conceptC,"overview.note":t.overview.note,copyright:t.copyright}}
function ContentEditor({t,lang}:{t:Translation,lang:Language}){
 const [fields,setFields]=useState<EditorFields>(()=>editorFields(t));const [status,setStatus]=useState("");const [saving,setSaving]=useState(false);
 useEffect(()=>{queueMicrotask(()=>{setFields(editorFields(t));setStatus("")})},[lang,t.landing.eyebrow,t.landing.titleA,t.landing.titleB,t.landing.subtitle,t.landing.conceptA,t.landing.conceptB,t.landing.conceptC,t.overview.note,t.copyright]);
 const labels:[keyof EditorFields,string,boolean][]=[["landing.eyebrow",t.dashboard.eyebrow,false],["landing.titleA",t.dashboard.headlineA,false],["landing.titleB",t.dashboard.headlineB,false],["landing.subtitle",t.dashboard.subtitle,true],["landing.conceptA",t.dashboard.conceptA,true],["landing.conceptB",t.dashboard.conceptB,true],["landing.conceptC",t.dashboard.conceptC,true],["overview.note",t.dashboard.creatorNote,true],["copyright",t.dashboard.copyrightLabel,false]];
 async function saveContent(){setSaving(true);setStatus("");const res=await fetch("/api/content",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,values:fields})}).catch(()=>null);setSaving(false);if(res?.ok){setStatus(t.dashboard.contentSaved);window.dispatchEvent(new Event("content-updated"))}else setStatus(t.dashboard.contentFailed)}
 return <section className="contentEditor"><div className="contentEditorHead"><div><span className="kicker">LIVE / {lang.toUpperCase()}</span><h2>{t.dashboard.editor}</h2><p>{t.dashboard.editorIntro}</p></div><span className="liveDot"><i/> LIVE</span></div><div className="editorGrid">{labels.map(([key,label,long])=><label key={key}><span>{label}</span>{long?<textarea value={fields[key]} onChange={e=>setFields({...fields,[key]:e.target.value})}/>:<input value={fields[key]} onChange={e=>setFields({...fields,[key]:e.target.value})}/>}</label>)}</div><div className="editorActions"><button className="primary" onClick={saveContent} disabled={saving}>{saving?t.dashboard.saving:t.dashboard.saveContent}</button>{status&&<small role="status">{status}</small>}</div></section>
}
function Footer({text}:{text:string}){return <footer className="copyright">{text}</footer>}
