"use client";

import { useEffect, useState } from "react";
import { applyTranslationOverrides, languageOptions, translations, type Language, type Translation } from "./i18n";
import { DesignerRosterManager, LiveGroups, LiveJournal, LiveLinks, LiveSurvey, LiveTasks, OwnerContentManager, OwnerOperations } from "./live-flows";

type View="home"|"tasks"|"survey"|"links"|"journal"|"groups"|"dashboard";
const views:View[]=["home","tasks","survey","links","journal","groups","dashboard"];
type ContentByLanguage = Record<Language, Record<string, string>>;
const emptyContent=Object.fromEntries(languageOptions.map(({value})=>[value,{}])) as ContentByLanguage;
const conceptEssayZh=[
"《WHAT 100 PEOPLE DO TO A GAME》是一项持续发生的参与式艺术计划。它从一个未完成的游戏出发，但真正被观察的并不是游戏能否成为一个标准产品，而是一百位彼此不同的人如何在接触、理解、误读、修改和传递它的过程中，让同一个起点逐渐产生无法预先设计的方向。每位参与者都不是被动的测试者，也不需要拥有专业背景。一次回答、一条规则、一张照片、一段声音、一个版本、一场对话或一次拒绝，都可能成为作品的一部分。",
"这里的“游戏”更像一种可以被共同触碰的媒介：它提供有限的边界，也留下足够多的空白。参与者可以遵循已有规则，也可以指出规则中的问题；可以补充内容，也可以删除内容；可以独自工作，也可以与临时组成的小组讨论。每一次行动都会留下痕迹，后来的参与者会面对前面的人已经改变过的材料，因此没有任何人面对的是完全相同的作品。作品不是沿着直线完成，而是在不断叠加、偏离和重新解释中形成。",
"数字网站承担的是入口、记录与协作空间，而不是游戏本体。公开访问者可以阅读项目概念，了解参与这项计划的人；收到邀请码的人才会进入具体的任务、问卷、版本链接、照片日志和私密小组。这样的分层不是为了制造神秘感，而是为了让公开信息与私人协作保持清楚边界，让不同年龄、语言和经验的人知道自己正在进入什么空间，以及自己的内容会被谁看到。",
"项目特别重视低压力参与。参与者无需注册公开账号，不必展示真实姓名，也不需要一次完成全部内容。任务可以保存为草稿，反馈可以之后修改，文件上传失败时应当能够重新尝试。界面尽量减少同时出现的选择，并通过明确的状态告诉使用者内容是否已经保存。这样的设计既考虑注意力容易分散的人，也考虑第一次使用数字协作工具的人，以及阅读、行动或感知方式不同的人。",
"一百并不是把人简化为数量。相反，它提醒项目必须面对差异：语言、地区、年龄、身体条件、教育背景、网络环境、游戏经验和表达习惯都会影响一个人如何理解同一件事。系统提供多语言入口，并允许文字、图片、声音、视频和文件等多种表达方式。没有一种表达天然高于另一种，也不是所有人都必须留下同样多的内容。参与可以很短，也可以持续很久；沉默、犹豫和中途退出同样被视为真实经验。",
"私密小组用于承载需要更稳定关系的讨论。只有项目 Owner 可以创建小组和决定成员，参与者只能看到自己被加入的空间。小组内可以建立不同文字频道、发送与修改消息、回应他人的内容、共享文件，并查看当前成员。群组内容不会自动变成公开材料；如果未来需要公开其中的片段，应再次确认语境、署名方式和参与者意愿。隐私不是附加选项，而是作品结构的一部分。",
"版本记录使变化能够被追踪。项目不会把最新版本包装成唯一正确的结果，而是保留每个阶段的链接、说明和反馈，让人看见一条规则为何出现、一段内容为何消失、一次讨论如何改变后续决定。照片日志保存过程中的现场、物件和行动，但它不是装饰性的宣传相册，而是另一种研究材料。文字无法说明的关系，有时会在图像、声音或时间顺序中被重新发现。",
"贡献度用于帮助整理劳动与责任，不用来判断谁更有价值。策划、设计、测试、翻译、记录、照顾、提出问题、维护秩序和修复错误都是不同形式的贡献。公开的共同创作者页面会持续更新名单顺序，但分数只是项目管理中的一种线索，不能完整代表一个人的影响。Owner 负责记录变动，同时需要保留原因，使排名不会成为脱离过程的竞争游戏。",
"最终，这项计划关心的不是一百个人能否把一个游戏做得更大、更快或更像市场上的成品，而是共同作者关系如何改变创作本身。当控制权被逐步分散，原作者需要学会倾听、等待和接受不确定性；参与者也需要决定自己愿意承担多少责任。网站保存这些决定的过程，使作品既能继续被修改，也能留下可回看的档案。它邀请人们进入的不是一个已经完成的世界，而是一项仍然允许被改变的共同实践。"
];
const conceptEssayEn=["WHAT 100 PEOPLE DO TO A GAME is an ongoing participatory art project that begins with an unfinished game and follows how one hundred different people interpret, alter, question, document, and pass it forward. Participants are not passive testers. A rule, response, image, sound, conversation, refusal, or revision can all become part of the work.","The website is the project’s entrance, archive, feedback centre, and private collaboration space—not the game itself. Public visitors can read the concept and meet the people involved. Invited participants can access tasks, surveys, builds, journals, files, and private groups. This separation keeps public information and private collaboration legible.","The project values low-pressure participation, anonymity, accessibility, multilingual access, recoverable drafts, and different forms of expression. Contribution is used to make labour and responsibility visible, not to measure anyone’s worth. The work remains open to change while preserving the decisions, disagreements, and care that shaped it."];

export function Studio(){
 const [lang,setLang]=useState<Language>("zh");const [entry,setEntry]=useState<"choose"|"public"|"invite">("choose");const [view,setView]=useState<View>("home");const [entered,setEntered]=useState(false);const [code,setCode]=useState("");const [notice,setNotice]=useState("");const [joining,setJoining]=useState(false);const [participant,setParticipant]=useState<{id:string;display_code:string}|null>(null);const [content,setContent]=useState<ContentByLanguage>(emptyContent);const t=applyTranslationOverrides(translations[lang],content[lang]);
 useEffect(()=>{queueMicrotask(()=>{const saved=localStorage.getItem("hundred-language") as Language|null;const browser=navigator.language.toLowerCase();setLang(saved&&translations[saved]?saved:browser.startsWith("ja")?"ja":browser.startsWith("en")?"en":"zh")})},[]);
 useEffect(()=>{queueMicrotask(()=>{const params=new URLSearchParams(location.search);const invite=params.get("invite");if(invite){setCode(invite);setEntry("invite")}else if(params.get("creator")==="1"){setEntered(true);setView("dashboard");history.replaceState({},"",location.pathname)}else if(params.get("public")==="1")setEntry("public")})},[]);
 useEffect(()=>{localStorage.setItem("hundred-language",lang);document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr"},[lang]);
 useEffect(()=>{let active=true;const load=()=>fetch("/api/content",{cache:"no-store"}).then(async r=>{if(!r.ok)return;const data=await r.json() as {content?:ContentByLanguage};if(active&&data.content)setContent({...emptyContent,...data.content})}).catch(()=>undefined);load();const timer=setInterval(load,15000);window.addEventListener("content-updated",load);return()=>{active=false;clearInterval(timer);window.removeEventListener("content-updated",load)}},[]);
 useEffect(()=>{if(!entered)return;const record=(kind:string,durationSeconds=0)=>fetch("/api/activity",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,surface:view,durationSeconds}),keepalive:true}).catch(()=>undefined);record("view");const heartbeat=setInterval(()=>record("heartbeat",60),60000);return()=>clearInterval(heartbeat)},[entered,view]);
 async function join(token=code){setJoining(true);setNotice("");const res=await fetch("/api/participant",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token})}).catch(()=>null);setJoining(false);if(res?.ok){const data=await res.json() as {participant:{id:string;display_code:string}};setParticipant(data.participant);setEntered(true);setView("home");history.replaceState({},"",location.pathname)}else setNotice(lang==="zh"?"邀请编号无效、已过期或已被撤销。":"This invitation is invalid, expired, or revoked.")}
 if(!entered&&entry==="choose")return <main className="entryGate"><div className="entryTop"><span>WHAT 100 PEOPLE DO TO A GAME</span><LanguageSwitcher lang={lang} setLang={setLang} label={t.language}/></div><section><span className="kicker">ACCESS / {lang==="zh"?"选择进入方式":"CHOOSE HOW TO ENTER"}</span><h1>{lang==="zh"?"你想怎样进入？":"How would you like to enter?"}</h1><div className="entryChoices"><button onClick={()=>setEntry("public")}><b>{lang==="zh"?"普通访问":"Public visit"}</b><span>{lang==="zh"?"阅读完整项目概念":"Read the full project concept"}</span><i>→</i></button><button onClick={()=>setEntry("invite")}><b>{lang==="zh"?"邀请码进入":"Enter with invitation"}</b><span>{lang==="zh"?"进入任务、问卷、文件与私密小组":"Access tasks, surveys, files, and private groups"}</span><i>→</i></button></div><button className="creatorEntry" onClick={()=>{setEntered(true);setView("dashboard")}}>{t.creatorSignIn}</button></section><Footer text={t.copyright}/></main>;
 if(!entered&&entry==="invite")return <main className="entryGate inviteGate"><div className="entryTop"><button onClick={()=>{setEntry("choose");setNotice("")}}>← {lang==="zh"?"返回":"Back"}</button><LanguageSwitcher lang={lang} setLang={setLang} label={t.language}/></div><section><span className="kicker">PRIVATE ACCESS</span><h1>{lang==="zh"?"填写邀请码":"Enter invitation code"}</h1><p>{lang==="zh"?"邀请码验证成功后才能进入协作区域。":"The collaboration area opens only after verification."}</p><div className="gateInvite"><input value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")join()}} placeholder={lang==="zh"?"邀请码":"Invitation code"}/><button className="primary" onClick={()=>join()} disabled={joining||!code.trim()}>{joining?(lang==="zh"?"正在验证…":"Checking…"):(lang==="zh"?"验证并进入":"Verify and enter")}</button></div>{notice&&<p className="gateError" role="alert">{notice}</p>}</section><Footer text={t.copyright}/></main>;
 if(!entered)return <main className="landing"><header className="top"><span className="mark">WHAT 100 PEOPLE DO TO A GAME</span><div><LanguageSwitcher lang={lang} setLang={setLang} label={t.language}/><a className="ghost peopleLink" href="/people">{lang==="zh"?"共同创作者":"People"}</a><button className="ghost" onClick={()=>setEntry("choose")}>{lang==="zh"?"重新选择":"Choose again"}</button></div></header><section className="hero"><div className="eyebrow">{t.landing.eyebrow}</div><h1>{t.landing.titleA}<br/><em>{t.landing.titleB}</em></h1><p>{t.landing.subtitle}</p><div className="heroActions"><button className="primary" onClick={()=>document.getElementById("concept")?.scrollIntoView()}>{t.landing.enter} →</button><a href="#concept">{t.landing.concept}</a></div><div className="orbit" aria-hidden="true"/></section><section id="concept" className="concept longConcept"><span>CONCEPT / {t.landing.conceptLabel}</span><h2>{t.landing.conceptA}<br/>{t.landing.conceptB}<br/>{t.landing.conceptC}</h2><div className="conceptEssay">{(lang==="zh"?conceptEssayZh:conceptEssayEn).map((p,i)=><p key={i}>{p}</p>)}</div><a className="peopleCta" href="/people">{lang==="zh"?"查看共同创作者":"Meet the people behind the project"} →</a></section><Footer text={t.copyright}/></main>;
 const navLabels=[t.nav.overview,t.nav.tasks,t.nav.survey,t.nav.links,t.nav.journal,t.nav.groups,t.nav.dashboard];
 const participantLabel=participant?.display_code||"OWNER";
 return <main className="app"><aside><button className="brand" onClick={()=>setView("home")}>WHAT 100<span>PEOPLE DO TO A GAME</span></button><nav aria-label="Navigation">{views.map((id,i)=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><b>{String(i+1).padStart(2,"0")}</b>{navLabels[i]}</button>)}</nav><div className="asideFoot"><span>{participantLabel}</span></div></aside><section className="workspace"><header className="worktop"><span>LIVE PROJECT</span><div><LanguageSwitcher lang={lang} setLang={setLang} label={t.language}/><span className="privacy">● {t.privacy}</span><button className="avatar" aria-label={participantLabel}>{participantLabel.slice(-2)}</button></div></header>{notice&&<div className="toast">✓ {notice}</div>}{view==="home"&&<Overview t={t} setView={setView} participantCode={participantLabel} lang={lang}/>} {view==="tasks"&&<LiveTasks t={t} lang={lang}/>} {view==="survey"&&<LiveSurvey t={t} lang={lang}/>} {view==="links"&&<LiveLinks t={t} lang={lang}/>} {view==="journal"&&<LiveJournal t={t} lang={lang}/>} {view==="groups"&&<LiveGroups t={t} lang={lang}/>} {view==="dashboard"&&<Dashboard t={t} lang={lang}/>}<Footer text={t.copyright}/></section></main>
}

function LanguageSwitcher({lang,setLang,label}:{lang:Language,setLang:(l:Language)=>void,label:string}){return <label className="languagePicker"><span><b aria-hidden="true">🌐</b>{label} / LANGUAGE</span><select aria-label={`${label} / Language`} value={lang} onChange={e=>setLang(e.target.value as Language)}>{languageOptions.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>}
function Overview({t,setView,participantCode,lang}:{t:Translation,setView:(v:View)=>void;participantCode:string;lang:Language}){const [summary,setSummary]=useState({activeTasks:0,submittedTasks:0,journalEntries:0,gameLinks:0,groups:0,activeSurveys:0});useEffect(()=>{fetch("/api/overview",{cache:"no-store"}).then(async r=>{if(r.ok)setSummary(await r.json())}).catch(()=>undefined)},[]);const cards=[{view:"tasks" as View,title:t.nav.tasks,count:summary.activeTasks},{view:"survey" as View,title:t.nav.survey,count:summary.activeSurveys},{view:"journal" as View,title:t.nav.journal,count:summary.journalEntries}];return <div className="page"><div className="intro"><span>{participantCode}</span><h1>{t.overview.welcome.replace("#042",participantCode)}</h1><p>{t.overview.gentle}</p></div><div className="progress"><div><b>{summary.activeTasks}</b><span>{lang==="zh"?"开放任务":"Open tasks"}</span></div><div><b>{summary.submittedTasks}</b><span>{lang==="zh"?"已提交":"Submitted"}</span></div><div><b>{summary.groups}</b><span>{lang==="zh"?"私密小组":"Private groups"}</span></div><div><b>{summary.gameLinks}</b><span>{lang==="zh"?"游戏版本":"Game builds"}</span></div></div><h2 className="sectionTitle">{t.overview.next}</h2><div className="taskGrid">{cards.map((x,i)=><button key={x.view} className={`task ${["coral","blue","green"][i]}`} onClick={()=>setView(x.view)}><span>{x.count}</span><h3>{x.title}</h3><i>→</i></button>)}</div><div className="note"><span>{t.overview.creator}</span><p>{t.overview.note}</p></div></div>}
type ContributionRow={id:string;display_code:string;contribution_score:number;activity_count:number;last_active_at:number|null};

function Dashboard({t,lang}:{t:Translation,lang:Language}){
 const [rows,setRows]=useState<ContributionRow[]>([]);const [locked,setLocked]=useState(false);const [selected,setSelected]=useState("");const [points,setPoints]=useState("1");const [reason,setReason]=useState("");const [message,setMessage]=useState("");const [search,setSearch]=useState("");const [now]=useState(()=>Date.now());
 const load=()=>fetch("/api/contributions",{cache:"no-store"}).then(async r=>{if(!r.ok){setLocked(true);return}const data=await r.json() as {participants?:ContributionRow[]};setLocked(false);setRows(data.participants||[]);setSelected(x=>x||data.participants?.[0]?.id||"")}).catch(()=>setLocked(true));
 useEffect(()=>{load()},[]);
 async function record(){const res=await fetch("/api/contributions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({participantId:selected,points:Number(points),reason})});if(res.ok){setReason("");setMessage(t.dashboard.success);await load()}else setMessage(t.dashboard.failure)}
 if(locked)return <div className="page narrow"><div className="kicker">{t.dashboard.label}</div><h1>{t.dashboard.lockedTitle}</h1><div className="lock">🔒 {t.dashboard.locked}</div><a className="primary signin" href="/signin-with-chatgpt?return_to=/?creator=1">{t.dashboard.signIn}</a></div>;
 const total=rows.reduce((s,r)=>s+Number(r.contribution_score||0),0);const locale=lang==="zh"?"zh-CN":lang==="ja"?"ja-JP":lang;const filtered=rows.filter(r=>r.display_code.toLowerCase().includes(search.toLowerCase()));
 function exportCsv(){const header=["participant","contribution_score","activity_count","last_active_at"];const data=filtered.map(r=>[r.display_code,r.contribution_score,r.activity_count,r.last_active_at?new Date(Number(r.last_active_at)).toISOString():""]);const csv=[header,...data].map(row=>row.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob(["\uFEFF",csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`w100-participants-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
 return <div className="page"><div className="kicker">{t.dashboard.label}</div><h1>{t.dashboard.title}</h1><OwnerOperations lang={lang} participants={rows} onParticipantsChanged={load}/><OwnerContentManager lang={lang}/><DesignerRosterManager lang={lang}/><ContentEditor t={t} lang={lang}/><div className="metrics">{[[String(rows.length),t.dashboard.recorded],[String(rows.reduce((s,r)=>s+Number(r.activity_count||0),0)),t.dashboard.events],[String(total),t.dashboard.total],[String(rows.filter(r=>r.last_active_at&&now-Number(r.last_active_at)<86400000).length),t.dashboard.daily]].map(([a,b])=><div key={b}><b>{a}</b><span>{b}</span></div>)}</div><section className="scorePanel"><div><span className="kicker">{t.dashboard.manual}</span><h2>{t.dashboard.manualTitle}</h2></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{rows.map(r=><option key={r.id} value={r.id}>{r.display_code}</option>)}</select><input type="number" min="-1000" max="1000" value={points} onChange={e=>setPoints(e.target.value)} aria-label={t.dashboard.points}/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder={t.dashboard.reason}/><button className="dark" onClick={record} disabled={!selected||!reason}>{t.dashboard.record}</button>{message&&<small>{message}</small>}</section><div className="dashboardTools"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={lang==="zh"?"按参与者编号筛选":"Filter by participant code"}/><button className="owner" onClick={exportCsv}>{lang==="zh"?"导出 CSV":"Export CSV"}</button></div><div className="table contributionTable"><div className="tr head"><span>{t.dashboard.person}</span><span>{t.dashboard.score}</span><span>{t.dashboard.activity}</span><span>{t.dashboard.recent}</span></div>{filtered.map(r=><div className="tr" key={r.id}><span>{r.display_code}</span><span><b>{r.contribution_score}</b></span><span>{r.activity_count}</span><span>{r.last_active_at?new Date(Number(r.last_active_at)).toLocaleString(locale):t.dashboard.never}</span></div>)}</div></div>
}

type EditorFields={
 "landing.eyebrow":string;"landing.titleA":string;"landing.titleB":string;"landing.subtitle":string;"landing.conceptA":string;"landing.conceptB":string;"landing.conceptC":string;"overview.note":string;copyright:string;
};
function editorFields(t:Translation):EditorFields{return{"landing.eyebrow":t.landing.eyebrow,"landing.titleA":t.landing.titleA,"landing.titleB":t.landing.titleB,"landing.subtitle":t.landing.subtitle,"landing.conceptA":t.landing.conceptA,"landing.conceptB":t.landing.conceptB,"landing.conceptC":t.landing.conceptC,"overview.note":t.overview.note,copyright:t.copyright}}
function ContentEditor({t,lang}:{t:Translation,lang:Language}){
 const [fields,setFields]=useState<EditorFields>(()=>editorFields(t));const [status,setStatus]=useState("");const [saving,setSaving]=useState(false);
 useEffect(()=>{queueMicrotask(()=>{setFields(editorFields(t));setStatus("")})},[lang,t.landing.eyebrow,t.landing.titleA,t.landing.titleB,t.landing.subtitle,t.landing.conceptA,t.landing.conceptB,t.landing.conceptC,t.overview.note,t.copyright]);
 const labels:[keyof EditorFields,string,boolean][]=[["landing.eyebrow",t.dashboard.eyebrow,false],["landing.titleA",t.dashboard.headlineA,false],["landing.titleB",t.dashboard.headlineB,false],["landing.subtitle",t.dashboard.subtitle,true],["landing.conceptA",t.dashboard.conceptA,true],["landing.conceptB",t.dashboard.conceptB,true],["landing.conceptC",t.dashboard.conceptC,true],["overview.note",t.dashboard.creatorNote,true],["copyright",t.dashboard.copyrightLabel,false]];
 async function saveContent(){setSaving(true);setStatus("");const res=await fetch("/api/content",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({locale:lang,values:fields})}).catch(()=>null);setSaving(false);if(res?.ok){setStatus(t.dashboard.contentSaved);window.dispatchEvent(new Event("content-updated"))}else setStatus(t.dashboard.contentFailed)}
 return <section className="contentEditor"><div className="contentEditorHead"><div><span className="kicker">LIVE / {lang.toUpperCase()}</span><h2>{t.dashboard.editor}</h2><p>{t.dashboard.editorIntro}</p></div><span className="liveDot"><i/> LIVE</span></div><div className="editorGrid">{labels.map(([key,label,long])=><label key={key}><span>{label}</span>{long?<textarea value={fields[key]} onChange={e=>setFields({...fields,[key]:e.target.value})}/>:<input value={fields[key]} onChange={e=>setFields({...fields,[key]:e.target.value})}/>}</label>)}</div><div className="editorActions"><button className="primary" onClick={saveContent} disabled={saving}>{saving?t.dashboard.saving:t.dashboard.saveContent}</button>{status&&<small role="status">{status}</small>}</div></section>
}
function Footer({text}:{text:string}){return <footer className="copyright">{text}</footer>}
