"use client";

import { useEffect, useMemo, useState } from "react";

type Lang = "zh" | "en";
type View = "home" | "tasks" | "survey" | "links" | "journal" | "groups" | "dashboard";

const copy = {
  zh: { project:"100人游戏计划", subtitle:"一场由一百个人共同留下痕迹的游戏创作实验。", enter:"使用邀请进入", concept:"阅读计划理念", welcome:"晚上好，林遥", today:"今天，只做一件事也很好。", progress:"你的参与进度", tasks:"任务", survey:"问卷", links:"试玩链接", journal:"照片日志", groups:"私密小组", dashboard:"创作者台", next:"接下来", save:"已自动保存", upload:"上传作品", nav:"项目导航", invite:"邀请编号", join:"进入参与空间" },
  en: { project:"The 100 People Game", subtitle:"A game-making experiment shaped by the traces of one hundred people.", enter:"Enter with invitation", concept:"Read the concept", welcome:"Good evening, Lin", today:"One thing today is enough.", progress:"Your contribution", tasks:"Tasks", survey:"Survey", links:"Game links", journal:"Photo journal", groups:"Private groups", dashboard:"Creator desk", next:"Up next", save:"Autosaved", upload:"Upload work", nav:"Project navigation", invite:"Invitation code", join:"Enter participant space" }
};

const taskData = [
  {id:1,title:"记录一个你想留住的声音",meta:"约 5 分钟 · 音频 / 文字",status:"进行中",tone:"coral"},
  {id:2,title:"为陌生人设计一条规则",meta:"约 10 分钟 · 文字",status:"待开始",tone:"blue"},
  {id:3,title:"上传今天的一张照片",meta:"约 3 分钟 · 图片",status:"已完成",tone:"green"},
];

export function Studio(){
 const [lang,setLang]=useState<Lang>("zh"); const [view,setView]=useState<View>("home"); const [entered,setEntered]=useState(false); const [code,setCode]=useState("100-042-LIN"); const [notice,setNotice]=useState("");
 const t=copy[lang];
 useEffect(()=>{ const draft=localStorage.getItem("hundred-draft"); if(draft) setNotice(t.save); },[view,t.save]);
 const nav=useMemo(()=>[["home","概览","Overview"],["tasks",t.tasks,t.tasks],["survey",t.survey,t.survey],["links",t.links,t.links],["journal",t.journal,t.journal],["groups",t.groups,t.groups],["dashboard",t.dashboard,t.dashboard]] as [View,string,string][],[t]);
 function saveDraft(){localStorage.setItem("hundred-draft",new Date().toISOString());setNotice(t.save);setTimeout(()=>setNotice(""),1800)}
 if(!entered) return <main className="landing"><header className="top"><a className="mark">100 / ONE HUNDRED</a><div><button className="ghost" onClick={()=>setLang(lang==="zh"?"en":"zh")}>{lang==="zh"?"EN":"中"}</button><button className="ghost" onClick={()=>setEntered(true)}>Creator sign in</button></div></header><section className="hero"><div className="eyebrow">AN OPEN ART PROJECT · 2026—</div><h1>一百个人，<br/><em>共同完成一场游戏。</em></h1><p>{t.subtitle}</p><div className="heroActions"><button className="primary" onClick={()=>setEntered(true)}>{t.enter} →</button><a href="#concept">{t.concept}</a></div><div className="orbit" aria-hidden="true"><span>01</span><span>27</span><span>64</span><span>100</span></div></section><section id="concept" className="concept"><span>CONCEPT / 理念</span><h2>每个人都不需要成为“玩家”。<br/>你留下的声音、规则、照片与反馈，<br/>本身就是作品的一部分。</h2><div className="invite"><label>{t.invite}<input value={code} onChange={e=>setCode(e.target.value)} /></label><button className="dark" onClick={()=>setEntered(true)}>{t.join}</button><small>无需注册 · 此链接只属于你 · No account required</small></div></section></main>;
 return <main className="app"><aside><button className="brand" onClick={()=>setView("home")}>100<span>人游戏计划</span></button><nav aria-label={t.nav}>{nav.map(([id,zh,en],i)=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><b>{String(i+1).padStart(2,"0")}</b>{lang==="zh"?zh:en}</button>)}</nav><div className="asideFoot"><button onClick={()=>setLang(lang==="zh"?"en":"zh")}>{lang==="zh"?"English":"中文"}</button><span>参与者 #042</span></div></aside><section className="workspace"><header className="worktop"><span>ROUND 01 · 14 AUG</span><div><span className="privacy">● 私密空间</span><button className="avatar" aria-label="个人菜单">林</button></div></header>{notice&&<div className="toast">✓ {notice}</div>}{view==="home"&&<Overview t={t} setView={setView}/>} {view==="tasks"&&<Tasks save={saveDraft}/>} {view==="survey"&&<Survey save={saveDraft}/>} {view==="links"&&<Links/>} {view==="journal"&&<Journal/>} {view==="groups"&&<Groups/>} {view==="dashboard"&&<Dashboard/>}</section></main>
}

function Overview({t,setView}:{t:any,setView:(v:View)=>void}){return <div className="page"><div className="intro"><span>参与者 / PARTICIPANT 042</span><h1>{t.welcome}</h1><p>{t.today}</p></div><div className="progress"><div><b>3</b><span>已完成</span></div><div><b>2</b><span>进行中</span></div><div><b>5</b><span>等待你</span></div><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="50"/><circle className="done" cx="60" cy="60" r="50"/><text x="60" y="66">30%</text></svg></div><h2 className="sectionTitle">{t.next}<span>3 ITEMS</span></h2><div className="taskGrid">{taskData.map(x=><button key={x.id} className={`task ${x.tone}`} onClick={()=>setView("tasks")}><span>{x.status}</span><h3>{x.title}</h3><p>{x.meta}</p><i>→</i></button>)}</div><div className="note"><span>来自创作者</span><p>“没有标准答案。慢慢来，你可以随时回来继续。”</p></div></div>}
function Tasks({save}:{save:()=>void}){const [text,setText]=useState("");return <div className="page narrow"><div className="kicker">TASK 02 / 规则采集</div><h1>为陌生人设计一条规则</h1><p className="lede">想象有一个你从未见过的人，将在不知道你的情况下遇见这条规则。</p><div className="prompt"><span>你的规则</span><textarea value={text} onChange={e=>setText(e.target.value)} onBlur={save} placeholder="写下任何长度的答案……"/><div><small>{text.length} 字 · 离开输入框时自动保存</small><button className="primary" onClick={save}>保存并继续 →</button></div></div><Upload/></div>}
function Survey({save}:{save:()=>void}){return <div className="page narrow"><div className="kicker">PLAYTEST / 试玩反馈</div><h1>刚才的体验，像什么？</h1><fieldset className="scale"><legend>我知道下一步该做什么</legend>{[1,2,3,4,5].map(n=><label key={n}><input type="radio" name="scale" onChange={save}/><span>{n}</span></label>)}</fieldset><label className="field">最想保留的一个瞬间<textarea onBlur={save}/></label><button className="primary" onClick={save}>提交反馈</button></div>}
function Links(){return <div className="page"><div className="kicker">BUILD LIBRARY / 版本库</div><h1>试玩链接</h1><div className="version"><div><span className="live">当前版本 · V0.7</span><h2>Listening Room</h2><p>2026.08.12 · Web · 中英双语</p></div><button className="primary">打开试玩 ↗</button></div>{["V0.6 · 走动测试","V0.5 · 声音原型"].map(v=><div className="history" key={v}><b>{v}</b><span>查看说明与历史反馈 →</span></div>)}</div>}
function Journal(){return <div className="page"><div className="kicker">PHOTO JOURNAL / 共同档案</div><h1>我们如何走到这里</h1><div className="photoGrid">{["桌上的二十七张纸","第一次公开试玩","雨天收集到的声音","第 64 位参与者"].map((x,i)=><article key={x} className={`ph p${i}`}><div>{String(i+1).padStart(2,"0")}</div><h3>{x}</h3><p>上海 · 2026</p></article>)}</div><Upload/></div>}
function Groups(){return <div className="page"><div className="kicker">PRIVATE GROUP / 仅成员可见</div><h1>声音小组 <small>8 人</small></h1><div className="chat"><div><b>阿愿</b><p>我把昨晚车站的环境声放进群文件了。</p><time>19:42</time></div><div><b>你</b><p>听到了，最后十秒特别像潮水。</p><time>19:48</time></div></div><label className="composer"><input placeholder="写给小组……"/><button>发送</button></label><div className="lock">🔒 群组、消息与文件仅对成员可见。只有项目 Owner 可以建立群组。</div></div>}
function Dashboard(){return <div className="page"><div className="kicker">CREATOR DASHBOARD / 权限：OWNER</div><h1>项目正在生长</h1><div className="metrics">{[["68","已加入"],["214","份提交"],["72%","任务完成率"],["9","活跃小组"]].map(([a,b])=><div key={b}><b>{a}</b><span>{b}</span></div>)}</div><div className="toolbar"><input placeholder="筛选参与者、任务或标签"/><select><option>全部轮次</option><option>Round 01</option></select><button className="dark">导出 CSV</button></div><div className="table"><div className="tr head"><span>参与者</span><span>进度</span><span>最近活动</span><span>状态</span></div>{[["#042 林遥","6 / 10","2 分钟前","活跃"],["#041 M.","10 / 10","昨天","完成"],["#040 陈海","3 / 10","3 天前","需关注"]].map(r=><div className="tr" key={r[0]}>{r.map(c=><span key={c}>{c}</span>)}</div>)}</div><button className="owner">＋ 建立私密小组（仅 Owner）</button></div>}
function Upload(){return <label className="upload"><input type="file" multiple/><span>＋</span><b>拖放或选择文件</b><small>照片、音频、视频、文档 · 最大 50 MB</small></label>}
