"use client";

import type { Language } from "./i18n";

export function WeekAnnouncementPage({lang,week}:{lang:Language;week:number}){
 const zh=lang==="zh";
 if(week!==0)return <section className="announcementBoard announcementEmpty"><header><div><span className="kicker">WEEK {week} · PROJECT NOTICE</span><h2>{zh?`Week ${week} 公告`:`Week ${week} announcement`}</h2></div><time>{zh?"项目公告":"Announcement"}</time></header><div><b>{zh?"本周公告尚未发布。":"This week's announcement has not been published yet."}</b><p>{zh?"发布后会集中显示在这里，不需要在其他页面查找。":"Once published, it will appear here so you do not need to search elsewhere."}</p></div></section>;
 return <section className="announcementBoard"><header><div><span className="kicker">WEEK 0 · PROJECT NOTICE</span><h2>{zh?"项目开始前须知":"Before the project begins"}</h2></div><time>{zh?"项目公告":"Announcement"}</time></header><div className="announcementLead"><b>{zh?"Week 0 准备事项":"Week 0 preparation"}</b><p>{zh?"Top 5 Games 已在微信群完成收集，参与者无需再次填写。请等待主策划 Hera 整理并上传至网站。目前只需按安排填写参与者信息问卷；已有完整想法的人可自愿提交电子提案。":"Top 5 Games has already been collected in WeChat, so participants do not need to submit it again. Please wait while Lead Designer Hera organises the responses and uploads them to the site. For now, complete the participant survey as arranged; those with a developed idea may optionally submit a digital proposal."}</p></div><details open><summary><b>01</b><span>{zh?"等待整理上传：Top 5 Games":"Awaiting upload: Top 5 Games"}</span></summary><div><p>{zh?"这一项已在微信群完成收集。这里不需要再次填写，请等待主策划 Hera 整理并上传至网站。":"This item has already been collected in the WeChat group. No further submission is needed here; please wait while Lead Designer Hera organises the responses and uploads them to the site."}</p></div></details><details><summary><b>02</b><span>{zh?"可选：Digital Proposal 电子提案":"Optional: Digital Proposal"}</span></summary><div><p>{zh?"如果你已经有较完整的游戏想法，可以提前提交；没有完整想法时不必为了提交而临时构思。提案没有固定格式或页数，重点是让其他人理解你的想法。":"If you already have a developed game idea, you may submit it early. Do not invent one just to complete this optional task. There is no required format or length; clarity is what matters."}</p><div className="proposalTopics">{[zh?"Concept · 核心概念":"Concept",zh?"Narrative · 叙事":"Narrative",zh?"Character Design · 角色设计":"Character Design",zh?"Mechanic · 游戏机制":"Mechanic",zh?"Visual / Art Style · 视觉与美术":"Visual / Art Style",zh?"Other · 声音、媒介、材料与技术":"Other · Sound, media, material and technology"].map(x=><span key={x}>{x}</span>)}</div><p>{zh?"不需要覆盖全部部分。文档、PDF、PPT、表格、备忘录截图、手写照片、草图、Moodboard 或 Lookbook 均可。可私发主策划 Hera，也可发到微信群供大家讨论。":"Include only the relevant sections. Documents, PDFs, slides, spreadsheets, screenshots, handwriting, sketches, moodboards and lookbooks are accepted. Send it privately to Lead Designer Hera or share it in the WeChat group."}</p></div></details><details><summary><b>03</b><span>{zh?"按安排填写：参与者信息问卷":"Complete as arranged: Participant survey"}</span></summary><div><p>{zh?"问卷用于了解参与者的背景、兴趣与擅长方向、相关经验、希望参与的部分、可投入时间，以及目前关注的主题。信息将用于人员协调、分组、工作安排和项目规划。":"The survey covers participants’ backgrounds, interests, experience, preferred areas of contribution, available time and current themes. It supports coordination, grouping, scheduling and project planning."}</p><p>{zh?"没有游戏制作经验完全没关系，经验多少不会决定谁的想法更重要。正式开始后的第一周将集中讨论 Theme、Concept、Mechanic 与最终制作方向，具体任务与分工会统一通知。":"No game-making experience is required, and experience does not determine whose ideas matter. Week 1 will focus on Theme, Concept, Mechanic and the final production direction; detailed tasks and roles will be announced together."}</p></div></details></section>;
}
