import { NextRequest, NextResponse } from "next/server";
import { d1, isOwner, participantId, r2 } from "../_shared";
const imageTypes=new Set(["image/jpeg","image/png","image/webp","image/heic","image/heif"]);

export async function GET(req:NextRequest){
  const participant=await participantId(req);if(!participant&&!isOwner(req))return NextResponse.json({error:"Invitation required"},{status:401});
  const id=req.nextUrl.searchParams.get("id")??"";
  if(id){const row=await d1().prepare("SELECT file_key, content_type, file_name FROM journal_entries WHERE id = ?").bind(id).first<{file_key:string;content_type:string|null;file_name:string|null}>();if(!row)return NextResponse.json({error:"Entry not found"},{status:404});const object=await r2().get(row.file_key);if(!object?.body)return NextResponse.json({error:"File missing"},{status:404});return new Response(object.body,{headers:{"content-type":row.content_type||"application/octet-stream","content-disposition":`inline; filename*=UTF-8''${encodeURIComponent(row.file_name||"journal")}`,"cache-control":"private, max-age=300"}})}
  const rows=await d1().prepare("SELECT id, title_zh, title_en, participant_id, content_type, file_name, occurred_at FROM journal_entries ORDER BY occurred_at DESC LIMIT 100").all();return NextResponse.json({entries:rows.results});
}
export async function POST(req:NextRequest){
  const participant=await participantId(req);if(!participant&&!isOwner(req))return NextResponse.json({error:"Invitation required"},{status:401});const form=await req.formData();const file=form.get("file");if(!(file instanceof File)||!file.size||file.size>20*1024*1024||!imageTypes.has(file.type))return NextResponse.json({error:"Image required (max 20 MB)"},{status:400});
  const titleZh=String(form.get("titleZh")??"").trim().slice(0,160);const titleEn=String(form.get("titleEn")??titleZh).trim().slice(0,160);if(!titleZh)return NextResponse.json({error:"Title required"},{status:400});const id=crypto.randomUUID();const author=participant??"owner";const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_").slice(-120)||"image";const key=`journal/${id}-${safe}`;await r2().put(key,file.stream(),{httpMetadata:{contentType:file.type}});const now=Date.now();await d1().prepare("INSERT INTO journal_entries (id, title_zh, title_en, file_key, participant_id, content_type, file_name, occurred_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").bind(id,titleZh,titleEn,key,author,file.type,file.name.slice(0,240),now).run();return NextResponse.json({entry:{id,title_zh:titleZh,title_en:titleEn,participant_id:author,content_type:file.type,file_name:file.name,occurred_at:now}},{status:201});
}
export async function DELETE(req:NextRequest){if(!isOwner(req))return NextResponse.json({error:"Only the Owner can remove journal entries"},{status:403});const id=req.nextUrl.searchParams.get("id")??"";const row=await d1().prepare("SELECT file_key FROM journal_entries WHERE id = ?").bind(id).first<{file_key:string}>();if(!row)return NextResponse.json({error:"Entry not found"},{status:404});await r2().delete(row.file_key);await d1().prepare("DELETE FROM journal_entries WHERE id = ?").bind(id).run();return NextResponse.json({ok:true})}
