"use client";
import {useEffect,useMemo,useState} from "react";
import {allQuestions,type Question} from "../survey/questions";
import {npcQuestions} from "../survey/npc-questions";

export type LeadResponse={id:string;wechat_name:string;survey_type?:"participant-portrait"|"npc-design";locale:string;payload:string;submitted_at:number};
type SurveyType="all"|"participant-portrait"|"npc-design";
const surveyLabel=(type:string)=>type==="npc-design"?"NPC设计问卷":"参与者创作画像";
const questionsFor=(type:string):Question[]=>type==="npc-design"?npcQuestions:allQuestions;
const parseAnswers=(payload:string):Record<string,unknown>=>{try{const value:unknown=JSON.parse(payload);return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{}}catch{return {}}};
const responseType=(row:LeadResponse)=>(row.survey_type||parseAnswers(row.payload)._surveyType)==="npc-design"?"npc-design":"participant-portrait";
const filled=(value:unknown)=>Array.isArray(value)?value.length>0:typeof value==="string"&&value.trim().length>0;

async function request(url:string,init?:RequestInit){
 const controller=typeof AbortController==="function"?new AbortController():null;
 let timer=0;
 try{return await Promise.race([fetch(url,{...init,cache:"no-store",...(controller?{signal:controller.signal}:{})}),new Promise<Response>((_,reject)=>{timer=window.setTimeout(()=>{controller?.abort();reject(new Error("timeout"))},12000)})])}
 finally{window.clearTimeout(timer)}
}

export function LeadDashboard({initialRows}:{initialRows?:LeadResponse[]}={}){
 const [rows,setRows]=useState<LeadResponse[]>(initialRows??[]),[ready,setReady]=useState(initialRows!==undefined),[name,setName]=useState(""),[code,setCode]=useState(""),[error,setError]=useState(""),[query,setQuery]=useState(""),[surveyType,setSurveyType]=useState<SurveyType>("all"),[selectedName,setSelectedName]=useState<string|null>(null),[loading,setLoading]=useState(initialRows===undefined),[signingIn,setSigningIn]=useState(false);
 async function load(){
  setLoading(true);
  try{const r=await request("/api/lead/responses");if(r.status===401){setReady(false);return}if(!r.ok)throw new Error("load");const data=await r.json();if(!Array.isArray(data.responses))throw new Error("data");setRows(data.responses);setReady(true);setError("")}
  catch{setError("回答加载失败，请检查网络后重试。 / Unable to load responses. Please retry.")}
  finally{setLoading(false)}
 }
 useEffect(()=>{if(initialRows===undefined)void load()},[initialRows]);
 useEffect(()=>{if(!selectedName)return;const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape")setSelectedName(null)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[selectedName]);
 async function login(e:React.FormEvent){e.preventDefault();if(signingIn)return;setSigningIn(true);setError("");try{const r=await request("/api/lead/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:name,password:code})});if(r.ok)await load();else setError("用户名或密码不正确 / Invalid username or password")}catch{setError("登录失败，请检查网络后重试。 / Sign-in failed. Please retry.")}finally{setSigningIn(false)}}
 const filtered=useMemo(()=>rows.filter(r=>r.wechat_name.toLowerCase().includes(query.toLowerCase())&&(surveyType==="all"||responseType(r)===surveyType)),[rows,query,surveyType]);
 const people=useMemo(()=>[...new Set(filtered.map(r=>r.wechat_name))].map(wechatName=>({wechatName,responses:rows.filter(r=>r.wechat_name===wechatName).sort((a,b)=>b.submitted_at-a.submitted_at)})),[filtered,rows]);
 const selected=selectedName?{wechatName:selectedName,responses:rows.filter(r=>r.wechat_name===selectedName).sort((a,b)=>b.submitted_at-a.submitted_at)}:null;
 function csv(){const headers=["survey_type","submitted_at","wechat_name","npc_name","payload"];const esc=(value:unknown)=>{const raw=String(value??"");const safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replace(/"/g,'""')}"`};const content=[headers.join(","),...filtered.map(r=>{const a=parseAnswers(r.payload) as Record<string,unknown>;return [responseType(r),new Date(r.submitted_at).toISOString(),r.wechat_name,a.npcName||"",r.payload].map(esc).join(",")})].join("\n");const blob=new Blob(["\ufeff"+content],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="what-100-people-questionnaires.csv";document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
 if(loading&&!ready)return <main className="lead-login"><p role="status">正在加载… / Loading…</p></main>;
 if(!ready)return <main className="lead-login"><form onSubmit={login}><p className="eyebrow">PRIVATE ACCESS</p><h1>主策划<br/><em>Lead Designer</em></h1><label className="lead-code-field"><span>用户名 / Username</span><input autoFocus autoComplete="username" value={name} onChange={e=>setName(e.target.value)}/></label><label className="lead-code-field"><span>密码 / Password</span><input type="password" autoComplete="current-password" value={code} onChange={e=>setCode(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<button className="button primary" disabled={signingIn}>{signingIn?"正在登录… / Signing in…":"进入 / Enter"}</button><a href="/survey">← 返回问卷</a></form></main>;
 return <main className="lead-shell"><header className="lead-head"><div><p className="eyebrow">WHAT 100 PEOPLE DO TO A GAME</p><h1>问卷回答 <em>{rows.length}</em></h1></div><div className="lead-head-actions"><button className="button ghost" onClick={()=>void load()} disabled={loading}>{loading?"正在加载…":"刷新回答"}</button><button className="button ghost" onClick={csv}>导出 CSV</button></div></header>{error&&<p role="alert" className="form-error">{error}</p>}<section className="filters"><input placeholder="搜索微信群聊名" value={query} onChange={e=>setQuery(e.target.value)}/><select value={surveyType} onChange={e=>setSurveyType(e.target.value as SurveyType)} aria-label="问卷类型"><option value="all">全部问卷类型</option><option value="participant-portrait">参与者创作画像</option><option value="npc-design">NPC设计问卷</option></select><span>{people.length} 位参与者 / {filtered.length} 份回答</span></section><section className="response-list">{people.map(person=>{const npc=person.responses.filter(r=>responseType(r)==="npc-design");const portrait=person.responses.filter(r=>responseType(r)==="participant-portrait");const latest=person.responses[0];const latestAnswers=parseAnswers(latest.payload) as Record<string,unknown>;return <button key={person.wechatName} className="response-card" onClick={()=>setSelectedName(person.wechatName)}><div><strong>{person.wechatName}</strong><span>{portrait.length?"画像 ✓":"画像 —"} · {npc.length?"NPC ✓":"NPC —"}</span></div><p>{String(latestAnswers.npcName||latestAnswers.gameIdea||latestAnswers.favoritePoint||"—")}</p><time>{new Date(latest.submitted_at).toLocaleString("zh-CN")}</time></button>})}</section>{selected&&<div className="profile-backdrop" onClick={()=>setSelectedName(null)}><article className="profile-sheet" onClick={e=>e.stopPropagation()}><button className="profile-close" aria-label="关闭回答详情 / Close answers" onClick={()=>setSelectedName(null)}>×</button><p className="eyebrow">PARTICIPANT QUESTIONNAIRES</p><h2>{selected.wechatName}</h2>{(["participant-portrait","npc-design"] as const).map(type=>{const response=selected.responses.find(r=>responseType(r)===type);if(!response)return <section className="response-type-empty" key={type}><h3>{surveyLabel(type)}</h3><p>尚未提交 / Not submitted</p></section>;const answers=parseAnswers(response.payload) as Record<string,unknown>;return <section className="response-type" key={type}><header><div><p className="eyebrow">{type==="npc-design"?"NPC DESIGN":"CREATIVE PORTRAIT"}</p><h3>{surveyLabel(type)}</h3></div><time>{new Date(response.submitted_at).toLocaleString("zh-CN")}</time></header>{questionsFor(type).map(q=>{const value=answers[q.id];if(!filled(value))return null;const display=Array.isArray(value)?value.map(x=>q.options?.find(o=>o.value===x)?.zh||x).join(" · "):q.options?.find(o=>o.value===value)?.zh||value;return <div className="response-answer" key={q.id}><h4>{q.zh}</h4><p>{String(display)}</p></div>})}</section>})}</article></div>}</main>;
}
