"use client";
import {useEffect,useMemo,useState} from "react";import {allQuestions} from "../survey/questions";
export type LeadResponse={id:string;wechat_name:string;locale:string;payload:string;submitted_at:number};
export function LeadDashboard({initialRows}:{initialRows?:LeadResponse[]}={}){const [rows,setRows]=useState<LeadResponse[]>(initialRows??[]),[ready,setReady]=useState(initialRows!==undefined),[name,setName]=useState(""),[code,setCode]=useState(""),[error,setError]=useState(""),[query,setQuery]=useState(""),[planning,setPlanning]=useState(""),[role,setRole]=useState(""),[selected,setSelected]=useState<LeadResponse|null>(null);async function load(){const r=await fetch("/api/lead/responses");if(r.ok){setRows((await r.json()).responses);setReady(true)}}useEffect(()=>{if(initialRows===undefined)load()},[]);async function login(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/lead/login",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify({username:name,password:code})});if(r.ok)load();else setError("用户名或密码不正确 / Invalid username or password")}
 const filtered=useMemo(()=>rows.filter(r=>{const a=JSON.parse(r.payload);return r.wechat_name.toLowerCase().includes(query.toLowerCase())&&(!planning||a.planningLevel===planning)&&(!role||(a.creativeRoles||[]).includes(role)||(a.technicalRoles||[]).includes(role))}),[rows,query,planning,role]);
 function csv(){const heads=["submitted_at",...allQuestions.map(q=>q.id)],esc=(v:unknown)=>{const raw=String(Array.isArray(v)?v.join(" | "):v??"");const safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replaceAll('"','""')}"`};const body=[heads.join(","),...filtered.map(r=>{const a=JSON.parse(r.payload);return [new Date(r.submitted_at).toISOString(),...allQuestions.map(q=>a[q.id])].map(esc).join(",")})].join("\n");const blob=new Blob(["\ufeff"+body],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="what-100-people-survey.csv";a.click();URL.revokeObjectURL(url)}
 if(!ready)return <main className="lead-login"><form onSubmit={login}><p className="eyebrow">PRIVATE ACCESS</p><h1>主策划<br/><em>Lead Designer</em></h1><label className="lead-code-field"><span>用户名 / Username</span><input autoFocus autoComplete="username" value={name} onChange={e=>setName(e.target.value)}/></label><label className="lead-code-field"><span>密码 / Password</span><input type="password" autoComplete="current-password" value={code} onChange={e=>setCode(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<button className="button primary">进入 / Enter</button><a href="/survey">← 返回问卷</a></form></main>;
 return <main className="lead-shell"><header className="lead-head"><div><p className="eyebrow">WHAT 100 PEOPLE DO TO A GAME</p><h1>参与者创作画像 <em>{rows.length}</em></h1></div><button className="button ghost" onClick={csv}>导出 CSV</button></header><section className="filters"><input placeholder="搜索微信群聊名" value={query} onChange={e=>setQuery(e.target.value)}/><select value={planning} onChange={e=>setPlanning(e.target.value)}><option value="">全部策划参与度</option><option value="deep">深度策划</option><option value="basic">基础策划 + 测试反馈</option></select><select value={role} onChange={e=>setRole(e.target.value)}><option value="">全部实现意向</option><option value="visual">视觉设计 / 插画</option><option value="sound">声音 / 音乐</option><option value="gameplay">玩法程序</option><option value="web">网页 / 互动技术</option><option value="none">暂不参与实现</option></select><span>{filtered.length} / {rows.length}</span></section><section className="response-list">{filtered.map(r=>{const a=JSON.parse(r.payload);return <button key={r.id} className="response-card" onClick={()=>setSelected(r)}><div><strong>{r.wechat_name}</strong><span>{a.planningLevel==="deep"?"深度策划":"基础策划 + 测试"}</span></div><p>{String(a.gameIdea||a.favoritePoint||"—")}</p><time>{new Date(r.submitted_at).toLocaleString("zh-CN")}</time></button>})}</section>{selected&&<div className="profile-backdrop" onClick={()=>setSelected(null)}><article className="profile-sheet" onClick={e=>e.stopPropagation()}><button className="profile-close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">CREATIVE PORTRAIT</p><h2>{selected.wechat_name}</h2><time>{new Date(selected.submitted_at).toLocaleString("zh-CN")}</time>{allQuestions.map(q=>{const a=JSON.parse(selected.payload),v=a[q.id];if(!filled(v))return null;const display=Array.isArray(v)?v.map((x:string)=>q.options?.find(o=>o.value===x)?.zh||x).join(" · "):q.options?.find(o=>o.value===v)?.zh||v;return <section key={q.id}><h3>{q.zh}</h3><p>{display}</p></section>})}</article></div>}</main>}
function filled(v:unknown){return Array.isArray(v)?v.length>0:typeof v==="string"&&v.trim().length>0}
