"use client";
import {useEffect,useMemo,useState} from "react";
import {allQuestions,type Question} from "../survey/questions";
import {npcQuestions} from "../survey/npc-questions";

export type LeadResponse={id:string;wechat_name:string;survey_type?:"participant-portrait"|"npc-design";locale:string;payload:string;submitted_at:number};
type SurveyType="all"|"participant-portrait"|"npc-design";
const surveyLabel=(type:string)=>type==="npc-design"?"NPC设计问卷":"参与者创作画像";
const questionsFor=(type:string):Question[]=>type==="npc-design"?npcQuestions:allQuestions;
const responseType=(row:LeadResponse)=>(row.survey_type||JSON.parse(row.payload)._surveyType)==="npc-design"?"npc-design":"participant-portrait";
const filled=(value:unknown)=>Array.isArray(value)?value.length>0:typeof value==="string"&&value.trim().length>0;

export function LeadDashboard({initialRows}:{initialRows?:LeadResponse[]}={}){
 const [rows,setRows]=useState<LeadResponse[]>(initialRows??[]),[ready,setReady]=useState(initialRows!==undefined),[name,setName]=useState(""),[code,setCode]=useState(""),[error,setError]=useState(""),[query,setQuery]=useState(""),[surveyType,setSurveyType]=useState<SurveyType>("all"),[selectedName,setSelectedName]=useState<string|null>(null);
 async function load(){const r=await fetch("/api/lead/responses");if(r.ok){setRows((await r.json()).responses);setReady(true)}}
 useEffect(()=>{if(initialRows===undefined)load()},[initialRows]);
 async function login(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/lead/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:name,password:code})});if(r.ok)load();else setError("用户名或密码不正确 / Invalid username or password")}
 const filtered=useMemo(()=>rows.filter(r=>r.wechat_name.toLowerCase().includes(query.toLowerCase())&&(surveyType==="all"||responseType(r)===surveyType)),[rows,query,surveyType]);
 const people=useMemo(()=>[...new Set(filtered.map(r=>r.wechat_name))].map(wechatName=>({wechatName,responses:rows.filter(r=>r.wechat_name===wechatName).sort((a,b)=>b.submitted_at-a.submitted_at)})),[filtered,rows]);
 const selected=selectedName?{wechatName:selectedName,responses:rows.filter(r=>r.wechat_name===selectedName).sort((a,b)=>b.submitted_at-a.submitted_at)}:null;
 function csv(){const headers=["survey_type","submitted_at","wechat_name","npc_name","payload"];const esc=(value:unknown)=>{const raw=String(value??"");const safe=/^[=+\-@]/.test(raw)?`'${raw}`:raw;return `"${safe.replaceAll('"','""')}"`};const content=[headers.join(","),...filtered.map(r=>{const a=JSON.parse(r.payload) as Record<string,unknown>;return [responseType(r),new Date(r.submitted_at).toISOString(),r.wechat_name,a.npcName||"",r.payload].map(esc).join(",")})].join("\n");const blob=new Blob(["\ufeff"+content],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="what-100-people-questionnaires.csv";a.click();URL.revokeObjectURL(url)}
 if(!ready)return <main className="lead-login"><form onSubmit={login}><p className="eyebrow">PRIVATE ACCESS</p><h1>主策划<br/><em>Lead Designer</em></h1><label className="lead-code-field"><span>用户名 / Username</span><input autoFocus autoComplete="username" value={name} onChange={e=>setName(e.target.value)}/></label><label className="lead-code-field"><span>密码 / Password</span><input type="password" autoComplete="current-password" value={code} onChange={e=>setCode(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<button className="button primary">进入 / Enter</button><a href="/survey">← 返回问卷</a></form></main>;
 return <main className="lead-shell"><header className="lead-head"><div><p className="eyebrow">WHAT 100 PEOPLE DO TO A GAME</p><h1>问卷回答 <em>{rows.length}</em></h1></div><button className="button ghost" onClick={csv}>导出 CSV</button></header><section className="filters"><input placeholder="搜索微信群聊名" value={query} onChange={e=>setQuery(e.target.value)}/><select value={surveyType} onChange={e=>setSurveyType(e.target.value as SurveyType)} aria-label="问卷类型"><option value="all">全部问卷类型</option><option value="participant-portrait">参与者创作画像</option><option value="npc-design">NPC设计问卷</option></select><span>{people.length} 位参与者 / {filtered.length} 份回答</span></section><section className="response-list">{people.map(person=>{const npc=person.responses.filter(r=>responseType(r)==="npc-design");const portrait=person.responses.filter(r=>responseType(r)==="participant-portrait");const latest=person.responses[0];const latestAnswers=JSON.parse(latest.payload) as Record<string,unknown>;return <button key={person.wechatName} className="response-card" onClick={()=>setSelectedName(person.wechatName)}><div><strong>{person.wechatName}</strong><span>{portrait.length?"画像 ✓":"画像 —"} · {npc.length?"NPC ✓":"NPC —"}</span></div><p>{String(latestAnswers.npcName||latestAnswers.gameIdea||latestAnswers.favoritePoint||"—")}</p><time>{new Date(latest.submitted_at).toLocaleString("zh-CN")}</time></button>})}</section>{selected&&<div className="profile-backdrop" onClick={()=>setSelectedName(null)}><article className="profile-sheet" onClick={e=>e.stopPropagation()}><button className="profile-close" onClick={()=>setSelectedName(null)}>×</button><p className="eyebrow">PARTICIPANT QUESTIONNAIRES</p><h2>{selected.wechatName}</h2>{(["participant-portrait","npc-design"] as const).map(type=>{const response=selected.responses.find(r=>responseType(r)===type);if(!response)return <section className="response-type-empty" key={type}><h3>{surveyLabel(type)}</h3><p>尚未提交 / Not submitted</p></section>;const answers=JSON.parse(response.payload) as Record<string,unknown>;return <section className="response-type" key={type}><header><div><p className="eyebrow">{type==="npc-design"?"NPC DESIGN":"CREATIVE PORTRAIT"}</p><h3>{surveyLabel(type)}</h3></div><time>{new Date(response.submitted_at).toLocaleString("zh-CN")}</time></header>{questionsFor(type).map(q=>{const value=answers[q.id];if(!filled(value))return null;const display=Array.isArray(value)?value.map(x=>q.options?.find(o=>o.value===x)?.zh||x).join(" · "):q.options?.find(o=>o.value===value)?.zh||value;return <div className="response-answer" key={q.id}><h4>{q.zh}</h4><p>{String(display)}</p></div>})}</section>})}</article></div>}</main>;
}
